window.NEWS_DATA = [
  {
    "국가": "국내",
    "매체": "한국경제TV",
    "제목": "삼성SDS, 1분기 영업이익 783억원…전년비 70%↓",
    "링크": "https://n.news.naver.com/mnews/article/215/0001249935",
    "요약": "삼성SDS는 연결기준 올해 1분기 영업이익이 지난해 동기 대비 70.8% 줄어든 783억 원으로 잠정 집계됐다고 23일 공시했다. 삼성SDS는 \"퇴직금 산정 기준 변경에 따른 퇴직급여비용 충당 1,120억 원을 일시",
    "이미지": "https://mimgnews.pstatic.net/image/origin/215/2026/04/23/1249935.jpg?type=nf220_150",
    "수집일시": "2026-04-23T08:45:51.409529",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "한국경제TV",
    "title": "삼성SDS, 1분기 영업이익 783억원…전년비 70%↓",
    "link": "https://n.news.naver.com/mnews/article/215/0001249935",
    "summary": "삼성SDS는 연결기준 올해 1분기 영업이익이 지난해 동기 대비 70.8% 줄어든 783억 원으로 잠정 집계됐다고 23일 공시했다. 삼성SDS는 \"퇴직금 산정 기준 변경에 따른 퇴직급여비용 충당 1,120억 원을 일시",
    "image": "https://mimgnews.pstatic.net/image/origin/215/2026/04/23/1249935.jpg?type=nf220_150",
    "collected_at": "2026-04-23T08:45:51.409529",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "",
    "curation_mode": "curation-fallback",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "뉴시스",
    "제목": "드림에이지, '별이되어라2' 6월 서비스 종료",
    "링크": "https://n.news.naver.com/mnews/article/003/0013906376",
    "요약": "2D 액션 MORPG(다중 사용자 온라인 역할수행게임) '별이되어라2: 베다의 기사들'이 서비스 2년여 만에 문을 닫는다. 드림에이지가 퍼블리싱하고 플린트가 개발한 이 게임은 오는 6월 26일 낮 12시 서비스를 종",
    "이미지": "https://mimgnews.pstatic.net/image/origin/003/2026/04/23/13906376.jpg?type=nf220_150",
    "수집일시": "2026-04-23T08:45:51.409529",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "뉴시스",
    "title": "드림에이지, '별이되어라2' 6월 서비스 종료",
    "link": "https://n.news.naver.com/mnews/article/003/0013906376",
    "summary": "2D 액션 MORPG(다중 사용자 온라인 역할수행게임) '별이되어라2: 베다의 기사들'이 서비스 2년여 만에 문을 닫는다. 드림에이지가 퍼블리싱하고 플린트가 개발한 이 게임은 오는 6월 26일 낮 12시 서비스를 종",
    "image": "https://mimgnews.pstatic.net/image/origin/003/2026/04/23/13906376.jpg?type=nf220_150",
    "collected_at": "2026-04-23T08:45:51.409529",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "",
    "curation_mode": "curation-fallback",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "조선비즈",
    "제목": "LG유플러스, 유심 업데이트·무료 교체 10일 만에 100만건 돌파",
    "링크": "https://n.news.naver.com/mnews/article/366/0001159105",
    "요약": "LG유플러스는 전 고객을 대상으로 진행 중인 유심(USIM) 업데이트 및 무료 교체 누적 건수가 시행 10일 만에 100만건을 넘어섰다고 23일 밝혔다. 지난 13일부터 22일까지 누적 유심 업데이트는 42만7385",
    "이미지": "https://mimgnews.pstatic.net/image/origin/366/2026/04/23/1159105.jpg?type=nf220_150",
    "수집일시": "2026-04-23T08:45:51.409529",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "조선비즈",
    "title": "LG유플러스, 유심 업데이트·무료 교체 10일 만에 100만건 돌파",
    "link": "https://n.news.naver.com/mnews/article/366/0001159105",
    "summary": "LG유플러스는 전 고객을 대상으로 진행 중인 유심(USIM) 업데이트 및 무료 교체 누적 건수가 시행 10일 만에 100만건을 넘어섰다고 23일 밝혔다. 지난 13일부터 22일까지 누적 유심 업데이트는 42만7385",
    "image": "https://mimgnews.pstatic.net/image/origin/366/2026/04/23/1159105.jpg?type=nf220_150",
    "collected_at": "2026-04-23T08:45:51.409529",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "",
    "curation_mode": "curation-fallback",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "중앙일보",
    "제목": "“韓반도체 최초” 엔비디아가 찍었다…1000억 잭팟 터진 이 회사",
    "링크": "https://n.news.naver.com/mnews/article/025/0003518414",
    "요약": "KAIST 창업원장이 세운 딥테크 스타트업 포인투테크놀로지(Point2 technology)가 엔비디아 등으로부터 1000억원 규모의 투자를 유치했다. 23일 KAIST에 따르면, 배현민 전기및전자공학부 교수 겸 창",
    "이미지": "https://mimgnews.pstatic.net/image/origin/025/2026/04/23/3518414.jpg?type=nf220_150",
    "수집일시": "2026-04-23T08:45:51.409529",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "중앙일보",
    "title": "“韓반도체 최초” 엔비디아가 찍었다…1000억 잭팟 터진 이 회사",
    "link": "https://n.news.naver.com/mnews/article/025/0003518414",
    "summary": "KAIST 창업원장이 세운 딥테크 스타트업 포인투테크놀로지(Point2 technology)가 엔비디아 등으로부터 1000억원 규모의 투자를 유치했다. 23일 KAIST에 따르면, 배현민 전기및전자공학부 교수 겸 창",
    "image": "https://mimgnews.pstatic.net/image/origin/025/2026/04/23/3518414.jpg?type=nf220_150",
    "collected_at": "2026-04-23T08:45:51.409529",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "",
    "curation_mode": "curation-fallback",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "머니투데이",
    "제목": "\"도깨비처럼 '단풍국' 로케 어때?\"…한-캐, 콘텐츠 공동제작 협정 체결",
    "링크": "https://n.news.naver.com/mnews/article/008/0005348211",
    "요약": "한국과 캐나다가 드라마, 다큐멘터리, 영화, 애니메이션 등 시청각 콘텐츠를 공동 제작하기 위한 협정을 체결했다. 방송미디어통신위원회와 캐나다 문화유산부는 22일(현지시간) 캐나다 오타와 문화유산부에서 '대한민국과 캐",
    "이미지": "https://mimgnews.pstatic.net/image/origin/008/2026/04/23/5348211.jpg?type=nf220_150",
    "수집일시": "2026-04-23T08:45:51.409529",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "머니투데이",
    "title": "\"도깨비처럼 '단풍국' 로케 어때?\"…한-캐, 콘텐츠 공동제작 협정 체결",
    "link": "https://n.news.naver.com/mnews/article/008/0005348211",
    "summary": "한국과 캐나다가 드라마, 다큐멘터리, 영화, 애니메이션 등 시청각 콘텐츠를 공동 제작하기 위한 협정을 체결했다. 방송미디어통신위원회와 캐나다 문화유산부는 22일(현지시간) 캐나다 오타와 문화유산부에서 '대한민국과 캐",
    "image": "https://mimgnews.pstatic.net/image/origin/008/2026/04/23/5348211.jpg?type=nf220_150",
    "collected_at": "2026-04-23T08:45:51.409529",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "",
    "curation_mode": "curation-fallback",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "연합뉴스",
    "제목": "지역이 스스로 R&D한다…지역 주도 과기혁신 촉진법 의결",
    "링크": "https://n.news.naver.com/mnews/article/001/0016039420",
    "요약": "지역별 과기혁신계획 5년마다 수립하고 과기전담기관 지정 지역별 고유 자산과 여건에 따라 전략산업을 스스로 육성할 수 있는 자율형 연구개발(R&D) 체계 법적 기반이 마련됐다. 과학기술정보통신부는 23일 국회 본회의에",
    "이미지": "https://mimgnews.pstatic.net/image/origin/001/2026/04/23/16039420.jpg?type=nf220_150",
    "수집일시": "2026-04-23T08:45:51.409529",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "연합뉴스",
    "title": "지역이 스스로 R&D한다…지역 주도 과기혁신 촉진법 의결",
    "link": "https://n.news.naver.com/mnews/article/001/0016039420",
    "summary": "지역별 과기혁신계획 5년마다 수립하고 과기전담기관 지정 지역별 고유 자산과 여건에 따라 전략산업을 스스로 육성할 수 있는 자율형 연구개발(R&D) 체계 법적 기반이 마련됐다. 과학기술정보통신부는 23일 국회 본회의에",
    "image": "https://mimgnews.pstatic.net/image/origin/001/2026/04/23/16039420.jpg?type=nf220_150",
    "collected_at": "2026-04-23T08:45:51.409529",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "",
    "curation_mode": "curation-fallback",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "블로터",
    "제목": "KT, 논란 일던 '이사회 사전승인' 규정 삭제…\"대표 책임경영 강화\"",
    "링크": "https://n.news.naver.com/mnews/article/293/0000083303",
    "요약": "KT가 최고경영책임자(CEO)의 경영 자율성을 지나치게 침해한다고 회사 안팎으로부터 지적을 받아 온 이사회 규정을 정기 주주총회 이후 열린 이사회 회의에서 폐기하고 사실상 개정 전으로 복원했다. KT는 최근 정기 주",
    "이미지": "https://mimgnews.pstatic.net/image/origin/293/2026/04/23/83303.jpg?type=nf220_150",
    "수집일시": "2026-04-23T08:45:51.409529",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "블로터",
    "title": "KT, 논란 일던 '이사회 사전승인' 규정 삭제…\"대표 책임경영 강화\"",
    "link": "https://n.news.naver.com/mnews/article/293/0000083303",
    "summary": "KT가 최고경영책임자(CEO)의 경영 자율성을 지나치게 침해한다고 회사 안팎으로부터 지적을 받아 온 이사회 규정을 정기 주주총회 이후 열린 이사회 회의에서 폐기하고 사실상 개정 전으로 복원했다. KT는 최근 정기 주",
    "image": "https://mimgnews.pstatic.net/image/origin/293/2026/04/23/83303.jpg?type=nf220_150",
    "collected_at": "2026-04-23T08:45:51.409529",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "",
    "curation_mode": "curation-fallback",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "전자신문",
    "제목": "촘촘한 데이터 학습·보수적인 태도, '금융 AI 에이전트' 신뢰도 높여[기획]",
    "링크": "https://n.news.naver.com/mnews/article/030/0003421179",
    "요약": "인공지능(AI) 에이전트에 구체적인 데이터를 학습시키고 답변에 관한 명확한 근거를 제시하도록 설계해야 실제 현장에서 믿을 수 있는 '금융 AI 에이전트'로서 역할을 수행할 수 있다는 목소리가 나왔다. 금융 AI 에이",
    "이미지": "https://mimgnews.pstatic.net/image/origin/030/2026/04/23/3421179.jpg?type=nf220_150",
    "수집일시": "2026-04-23T08:45:51.409529",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "전자신문",
    "title": "촘촘한 데이터 학습·보수적인 태도, '금융 AI 에이전트' 신뢰도 높여[기획]",
    "link": "https://n.news.naver.com/mnews/article/030/0003421179",
    "summary": "인공지능(AI) 에이전트에 구체적인 데이터를 학습시키고 답변에 관한 명확한 근거를 제시하도록 설계해야 실제 현장에서 믿을 수 있는 '금융 AI 에이전트'로서 역할을 수행할 수 있다는 목소리가 나왔다. 금융 AI 에이",
    "image": "https://mimgnews.pstatic.net/image/origin/030/2026/04/23/3421179.jpg?type=nf220_150",
    "collected_at": "2026-04-23T08:45:51.409529",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "",
    "curation_mode": "curation-fallback",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "지디넷코리아",
    "제목": "'총파업 勢과시' 삼성전자 노조...체크오프 발동",
    "링크": "https://n.news.naver.com/mnews/article/092/0002419947",
    "요약": "삼성전자 초기업노동조합이 5월 총파업을 재확인하며 노사 갈등이 최고조에 달했다. 초기업노조는 23일 평택캠퍼스에서 개최한 결의대회에서 '체크오프(조합비 일괄공제)'를 도입했다. 그간 노출을 자제했던 노조가 조직력을",
    "이미지": "https://mimgnews.pstatic.net/image/origin/092/2026/04/23/2419947.jpg?type=nf220_150",
    "수집일시": "2026-04-23T08:45:51.409529",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "지디넷코리아",
    "title": "'총파업 勢과시' 삼성전자 노조...체크오프 발동",
    "link": "https://n.news.naver.com/mnews/article/092/0002419947",
    "summary": "삼성전자 초기업노동조합이 5월 총파업을 재확인하며 노사 갈등이 최고조에 달했다. 초기업노조는 23일 평택캠퍼스에서 개최한 결의대회에서 '체크오프(조합비 일괄공제)'를 도입했다. 그간 노출을 자제했던 노조가 조직력을",
    "image": "https://mimgnews.pstatic.net/image/origin/092/2026/04/23/2419947.jpg?type=nf220_150",
    "collected_at": "2026-04-23T08:45:51.409529",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "",
    "curation_mode": "curation-fallback",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "비즈워치",
    "제목": "이준희 삼성SDS 사장 컨콜 등판…베일 벗은 10조 투자",
    "링크": "https://n.news.naver.com/mnews/article/648/0000046552",
    "요약": "최근 1조2000억원 규모의 실탄을 추가로 확보한 삼성SDS가 2031년까지 10조원의 투자 계획을 공개했다. 이번 투자는 AI 풀스택 기업으로 도약에 방점이 찍혔다. 새로운 먹거리로 떠오른 AI 데이터센터(AIDC",
    "이미지": "https://mimgnews.pstatic.net/image/origin/648/2026/04/23/46552.jpg?type=nf220_150",
    "수집일시": "2026-04-23T08:45:51.409529",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "비즈워치",
    "title": "이준희 삼성SDS 사장 컨콜 등판…베일 벗은 10조 투자",
    "link": "https://n.news.naver.com/mnews/article/648/0000046552",
    "summary": "최근 1조2000억원 규모의 실탄을 추가로 확보한 삼성SDS가 2031년까지 10조원의 투자 계획을 공개했다. 이번 투자는 AI 풀스택 기업으로 도약에 방점이 찍혔다. 새로운 먹거리로 떠오른 AI 데이터센터(AIDC",
    "image": "https://mimgnews.pstatic.net/image/origin/648/2026/04/23/46552.jpg?type=nf220_150",
    "collected_at": "2026-04-23T08:45:51.409529",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "",
    "curation_mode": "curation-fallback",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "매일경제",
    "제목": "KT 이사회, 인사권 내려 놓는다...지배구조 개편 본격화",
    "링크": "https://n.news.naver.com/mnews/article/009/0005670465",
    "요약": "KT가 경영 효율성을 높이기 위해 대표이사의 인사와 조직 운영 권한을 대폭 강화하는 지배구조 개편을 단행합니다. 기존에는 조직을 바꿀 때마다 이사회의 사전 승인이 필요했지만, 앞으로는 대표의 자율적인 판단하에 더욱 빠르고 민첩하게 기업을 이끌 수 있게 됩니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/009/2026/04/23/5670465.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:43:31.031676",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "매일경제",
    "title": "KT 이사회, 인사권 내려 놓는다...지배구조 개편 본격화",
    "link": "https://n.news.naver.com/mnews/article/009/0005670465",
    "summary": "KT가 경영 효율성을 높이기 위해 대표이사의 인사와 조직 운영 권한을 대폭 강화하는 지배구조 개편을 단행합니다. 기존에는 조직을 바꿀 때마다 이사회의 사전 승인이 필요했지만, 앞으로는 대표의 자율적인 판단하에 더욱 빠르고 민첩하게 기업을 이끌 수 있게 됩니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/009/2026/04/23/5670465.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:43:31.031676",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "전자신문",
    "제목": "웹케시, 핀테크 기업 넘어 '금융 AI 에이전트' 기업으로 도약[기획]",
    "링크": "https://n.news.naver.com/mnews/article/030/0003421138",
    "요약": "웹케시가 단순한 금융 서비스 기업을 넘어, 사용자의 업무를 스스로 돕는 ‘금융 AI 에이전트’ 전문 기업으로의 대전환을 선포했습니다. 최근 개최된 대규모 컨퍼런스에서 인공지능이 복잡한 금융 데이터를 분석하고 실무를 대신 처리해주는 미래형 금융 서비스의 청사진을 공개해 업계의 큰 주목을 받았습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/030/2026/04/23/3421138.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:43:31.031676",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "전자신문",
    "title": "웹케시, 핀테크 기업 넘어 '금융 AI 에이전트' 기업으로 도약[기획]",
    "link": "https://n.news.naver.com/mnews/article/030/0003421138",
    "summary": "웹케시가 단순한 금융 서비스 기업을 넘어, 사용자의 업무를 스스로 돕는 ‘금융 AI 에이전트’ 전문 기업으로의 대전환을 선포했습니다. 최근 개최된 대규모 컨퍼런스에서 인공지능이 복잡한 금융 데이터를 분석하고 실무를 대신 처리해주는 미래형 금융 서비스의 청사진을 공개해 업계의 큰 주목을 받았습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/030/2026/04/23/3421138.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:43:31.031676",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "파이낸셜뉴스",
    "제목": "LG U+ 시각장애인 유심 교체 센터 가보니…\"접근성 문제 해소\"[르포]",
    "링크": "https://n.news.naver.com/mnews/article/014/0005512458",
    "요약": "LG유플러스가 시각장애인 복지관에 전용 유심 교체 센터를 마련해 디지털 취약계층의 정보 접근성을 대폭 강화했습니다. 전문가의 직접적인 도움을 통해 시각장애인이 겪었던 통신 서비스 이용의 불편함을 해소하고, 누구나 기술의 혜택을 평등하게 누릴 수 있는 환경을 조성하고 있습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/014/2026/04/23/5512458.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:43:31.031676",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "파이낸셜뉴스",
    "title": "LG U+ 시각장애인 유심 교체 센터 가보니…\"접근성 문제 해소\"[르포]",
    "link": "https://n.news.naver.com/mnews/article/014/0005512458",
    "summary": "LG유플러스가 시각장애인 복지관에 전용 유심 교체 센터를 마련해 디지털 취약계층의 정보 접근성을 대폭 강화했습니다. 전문가의 직접적인 도움을 통해 시각장애인이 겪었던 통신 서비스 이용의 불편함을 해소하고, 누구나 기술의 혜택을 평등하게 누릴 수 있는 환경을 조성하고 있습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/014/2026/04/23/5512458.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:43:31.031676",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "뉴스1",
    "제목": "\"감정 없어 더 무섭다\"…피지컬 AI에 패한 日탁구선수들 [영상]",
    "링크": "https://n.news.naver.com/mnews/article/421/0008908307",
    "요약": "소니가 개발한 AI 탁구 로봇이 인간 프로 선수를 상대로 승리를 거두며 스포츠계에 큰 놀라움을 안겼습니다. 감정의 동요 없이 오직 정밀한 데이터와 계산만으로 움직이는 '피지컬 AI'의 등장은 로봇이 인간의 신체적 한계를 넘어서는 새로운 시대가 열렸음을 시사합니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/421/2026/04/23/8908307.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:43:31.031676",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "뉴스1",
    "title": "\"감정 없어 더 무섭다\"…피지컬 AI에 패한 日탁구선수들 [영상]",
    "link": "https://n.news.naver.com/mnews/article/421/0008908307",
    "summary": "소니가 개발한 AI 탁구 로봇이 인간 프로 선수를 상대로 승리를 거두며 스포츠계에 큰 놀라움을 안겼습니다. 감정의 동요 없이 오직 정밀한 데이터와 계산만으로 움직이는 '피지컬 AI'의 등장은 로봇이 인간의 신체적 한계를 넘어서는 새로운 시대가 열렸음을 시사합니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/421/2026/04/23/8908307.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:43:31.031676",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "지디넷코리아",
    "제목": "삼성SDS \"KKR, 이사회 옵저버 참여…포트폴리오 협력\"[컨콜]",
    "링크": "https://n.news.naver.com/mnews/article/092/0002419942",
    "요약": "삼성SDS가 세계적인 투자사 KKR과 손잡고 글로벌 시장 공략에 속도를 냅니다. KKR은 이사회 참관인으로 참여해 경영 의사결정을 지원하며, 자신들이 보유한 방대한 글로벌 기업 네트워크와 삼성SDS의 IT 기술을 연결하는 가교 역할을 할 예정입니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/092/2026/04/23/2419942.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:43:31.031676",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "지디넷코리아",
    "title": "삼성SDS \"KKR, 이사회 옵저버 참여…포트폴리오 협력\"[컨콜]",
    "link": "https://n.news.naver.com/mnews/article/092/0002419942",
    "summary": "삼성SDS가 세계적인 투자사 KKR과 손잡고 글로벌 시장 공략에 속도를 냅니다. KKR은 이사회 참관인으로 참여해 경영 의사결정을 지원하며, 자신들이 보유한 방대한 글로벌 기업 네트워크와 삼성SDS의 IT 기술을 연결하는 가교 역할을 할 예정입니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/092/2026/04/23/2419942.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:43:31.031676",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "아시아경제",
    "제목": "KAIST 딥테크 '포인투테크놀로지', 엔비디아 투자 유치",
    "링크": "https://n.news.naver.com/mnews/article/277/0005753607",
    "요약": "KAIST 교수와 제자들이 함께 설립한 딥테크 스타트업 '포인투테크놀로지'가 글로벌 AI 반도체 거물인 엔비디아로부터 투자를 유치했습니다. 초고속 데이터 전송 기술을 전문으로 하는 이 기업은 이번 파트너십을 통해 차세대 네트워크 시장을 선도할 수 있는 강력한 발판을 마련하게 되었습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/277/2026/04/23/5753607.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:43:31.031676",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "아시아경제",
    "title": "KAIST 딥테크 '포인투테크놀로지', 엔비디아 투자 유치",
    "link": "https://n.news.naver.com/mnews/article/277/0005753607",
    "summary": "KAIST 교수와 제자들이 함께 설립한 딥테크 스타트업 '포인투테크놀로지'가 글로벌 AI 반도체 거물인 엔비디아로부터 투자를 유치했습니다. 초고속 데이터 전송 기술을 전문으로 하는 이 기업은 이번 파트너십을 통해 차세대 네트워크 시장을 선도할 수 있는 강력한 발판을 마련하게 되었습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/277/2026/04/23/5753607.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:43:31.031676",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "MBN",
    "제목": "'캐나다 펀드' 로 드라마·영화 제작을?...한-캐나다 협정 체결",
    "링크": "https://n.news.naver.com/mnews/article/057/0001946009",
    "요약": "한국과 캐나다가 손을 잡고 드라마와 영화 같은 영상 콘텐츠를 함께 만들기로 약속했습니다. 이번 협정을 통해 우리나라 제작사들이 캐나다의 자금 지원을 받으며 전 세계 시청자들을 사로잡을 고품질 콘텐츠를 더 활발하게 제작할 수 있을 것으로 기대됩니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/057/2026/04/23/1946009.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:43:31.031676",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "MBN",
    "title": "'캐나다 펀드' 로 드라마·영화 제작을?...한-캐나다 협정 체결",
    "link": "https://n.news.naver.com/mnews/article/057/0001946009",
    "summary": "한국과 캐나다가 손을 잡고 드라마와 영화 같은 영상 콘텐츠를 함께 만들기로 약속했습니다. 이번 협정을 통해 우리나라 제작사들이 캐나다의 자금 지원을 받으며 전 세계 시청자들을 사로잡을 고품질 콘텐츠를 더 활발하게 제작할 수 있을 것으로 기대됩니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/057/2026/04/23/1946009.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:43:31.031676",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "India’s app market is booming — but global platforms are capturing most of the gains",
    "링크": "https://techcrunch.com/2026/04/22/indias-app-market-is-booming-but-global-platforms-are-capturing-most-of-the-gains/",
    "수집일시": "2026-04-23T17:44:36.441743",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "Shade lands $14M to let creative teams search their video libraries in plain English",
    "링크": "https://techcrunch.com/2026/04/22/shade-lands-14m-to-let-creative-teams-search-their-video-libraries-in-plain-english/",
    "수집일시": "2026-04-23T17:44:36.441821",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "Tesla just increased its spending plan to $25B — here’s where the money is going",
    "링크": "https://techcrunch.com/2026/04/22/tesla-just-increased-its-capex-to-25b-heres-where-the-money-is-going/",
    "수집일시": "2026-04-23T17:44:36.441890",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "Google updates Workspace to make AI your new office intern",
    "링크": "https://techcrunch.com/2026/04/22/google-updates-workspace-to-make-ai-your-new-office-intern/",
    "수집일시": "2026-04-23T17:44:36.441958",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "Elon Musk admits millions of Tesla owners need upgrades for true ‘Full Self-Driving’",
    "링크": "https://techcrunch.com/2026/04/22/elon-musk-admits-millions-of-tesla-owners-need-upgrades-for-true-full-self-driving/",
    "수집일시": "2026-04-23T17:44:36.442035",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "Hands on with X’s new AI-powered custom feeds",
    "링크": "https://techcrunch.com/2026/04/22/hands-on-with-xs-new-ai-powered-custom-feeds/",
    "수집일시": "2026-04-23T17:44:36.442109",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "LinkedIn’s CEO is moving on; please hold your tearful video tributes",
    "링크": "https://techcrunch.com/2026/04/22/linkedins-ceo-is-moving-on-please-hold-your-tearful-video-tributes/",
    "수집일시": "2026-04-23T17:44:36.442202",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "Tesla Q1 revenue rises, driven by EV sales and FSD subscriptions",
    "링크": "https://techcrunch.com/2026/04/22/tesla-q1-revenue-rises-driven-by-ev-sales-and-fsd-subscriptions/",
    "수집일시": "2026-04-23T17:44:36.442277",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "NASA’s Artemis II moon mission shows space-to-Earth laser comms can scale",
    "링크": "https://techcrunch.com/2026/04/22/nasas-artemis-ii-moon-mission-shows-space-to-earth-laser-comms-can-scale/",
    "수집일시": "2026-04-23T17:44:36.442371",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "How SpaceX preempted a $2B fundraise with a $60B buyout offer",
    "링크": "https://techcrunch.com/2026/04/22/how-spacex-preempted-a-2b-fundraise-with-a-60b-buyout-offer/",
    "수집일시": "2026-04-23T17:44:36.442438",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "Honor’s new phones look like iPhones for Android",
    "링크": "https://www.theverge.com/gadgets/917301/honors-new-phones-look-like-iphones-for-android",
    "수집일시": "2026-04-23T17:44:37.556972",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "The Iranian women Trump &#8216;saved&#8217; from execution are simultaneously real and AI-manipulated",
    "링크": "https://www.theverge.com/policy/917180/trump-iran-ai-women-bita-hemmati",
    "수집일시": "2026-04-23T17:44:37.557525",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "Elon Musk admits that millions of Tesla vehicles won&#8217;t get unsupervised FSD",
    "링크": "https://www.theverge.com/transportation/917167/elon-musk-tesla-hw3-fsd",
    "수집일시": "2026-04-23T17:44:37.558047",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "X is going to let Grok curate your timeline",
    "링크": "https://www.theverge.com/tech/917113/x-ai-grok-timeline-curation",
    "수집일시": "2026-04-23T17:44:37.558587",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "Tesla&#8217;s revenue rises again as it prepares for more AI and robotics",
    "링크": "https://www.theverge.com/transportation/915217/tesla-q1-2026-earnings-profit-revenue",
    "수집일시": "2026-04-23T17:44:37.559150",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "AI failure could trigger the next financial crisis, warns Elizabeth Warren",
    "링크": "https://www.theverge.com/policy/917026/ai-economy-bubble-elizabeth-warren",
    "수집일시": "2026-04-23T17:44:37.559714",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "OpenAI now lets teams make custom bots that can do work on their own",
    "링크": "https://www.theverge.com/ai-artificial-intelligence/917065/openai-chatgpt-workspace-agents-custom-teams-bots",
    "수집일시": "2026-04-23T17:44:37.560922",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "Alexis Ohanian shocks Washington with pro-immigration remarks",
    "링크": "https://www.theverge.com/column/916949/alexis-ohanian-pro-immigration-remarks",
    "수집일시": "2026-04-23T17:44:37.561088",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "Former MrBeast exec sues over ‘years’ of alleged harassment",
    "링크": "https://www.theverge.com/tech/916903/mrbeast-sexual-harassment-lawsuit",
    "수집일시": "2026-04-23T17:44:37.561256",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "Ember’s self-heating smart mug is more than $50 off ahead of Mother’s Day",
    "링크": "https://www.theverge.com/gadgets/916818/ember-smart-mug-2-mothers-day-sale-2026-deal",
    "수집일시": "2026-04-23T17:44:37.561399",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "Hoka Coupon Codes: 30% Off | April 2026",
    "링크": "https://www.wired.com/story/hoka-coupon-code/",
    "수집일시": "2026-04-23T17:44:38.838215",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "Verizon Promo Codes: $200 Verizon Gift Cards | April 2026",
    "링크": "https://www.wired.com/story/verizon-promo-code/",
    "수집일시": "2026-04-23T17:44:38.838370",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "Dermstore Promo Codes: 25% Off",
    "링크": "https://www.wired.com/story/dermstore-promo-code/",
    "수집일시": "2026-04-23T17:44:38.838480",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "Chirp Discount Codes and Deals: Save Up to 67%",
    "링크": "https://www.wired.com/story/chirp-discount-code/",
    "수집일시": "2026-04-23T17:44:38.838585",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "15% Off Adidas Promo Code | April 2026",
    "링크": "https://www.wired.com/story/adidas-promo-code/",
    "수집일시": "2026-04-23T17:44:38.838711",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "Sam Altman’s Orb Company Promoted a Bruno Mars Partnership That Doesn't Exist",
    "링크": "https://www.wired.com/story/sam-altman-orb-company-bruno-mars-partnership-fake/",
    "수집일시": "2026-04-23T17:44:38.838867",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "US Senate Candidate Caught Insider Trading on Kalshi Says He Did It on Purpose",
    "링크": "https://www.wired.com/story/us-senate-candidate-caught-insider-trading-on-kalshi-says-he-did-it-on-purpose/",
    "수집일시": "2026-04-23T17:44:38.839031",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "Scientists Gave Cocaine to Salmon and You Will Absolutely Believe What Happened Next",
    "링크": "https://www.wired.com/story/cocaine-fueled-wild-salmon-swam-twice-as-far-as-sober-ones/",
    "수집일시": "2026-04-23T17:44:38.839166",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "5 AI Models Tried to Scam Me. Some of Them Were Scary Good",
    "링크": "https://www.wired.com/story/ai-model-phishing-attack-cybersecurity/",
    "수집일시": "2026-04-23T17:44:38.839330",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "New York Bans Government Employees from Insider Trading on Prediction Markets",
    "링크": "https://www.wired.com/story/new-york-bans-government-employees-prediction-markets/",
    "수집일시": "2026-04-23T17:44:38.839456",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "Crypto scam lures ships into Strait of Hormuz, falsely promising safe passage",
    "링크": "https://arstechnica.com/security/2026/04/crypto-scam-lures-ships-into-strait-of-hormuz-falsely-promising-safe-passage/",
    "수집일시": "2026-04-23T17:44:40.040878",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "Tesla reports Q1 2026 earnings: Still profitable",
    "링크": "https://arstechnica.com/cars/2026/04/tesla-reports-q1-2026-earnings-still-profitable/",
    "수집일시": "2026-04-23T17:44:40.041092",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "Our newsroom AI policy",
    "링크": "https://arstechnica.com/staff/2026/04/our-newsroom-ai-policy/",
    "수집일시": "2026-04-23T17:44:40.041183",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "Lawsuit: Nintendo is getting tariff refunds—its customers should get them instead",
    "링크": "https://arstechnica.com/tech-policy/2026/04/lawsuit-nintendo-is-getting-tariff-refunds-its-customers-should-get-them-instead/",
    "수집일시": "2026-04-23T17:44:40.041298",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "RFK Jr. won't back CDC director on vaccines as agency scraps positive data",
    "링크": "https://arstechnica.com/health/2026/04/rfk-jr-doubles-down-on-vaccine-meddling-as-cdc-junks-scientific-study/",
    "수집일시": "2026-04-23T17:44:40.041369",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "You want your Moon landings in HD? So does NASA—here's how it's happening.",
    "링크": "https://arstechnica.com/space/2026/04/you-want-your-moon-landings-in-hdtv-so-does-nasa-heres-how-its-happening/",
    "수집일시": "2026-04-23T17:44:40.041424",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "Microsoft issues emergency update for macOS and Linux ASP.NET threat",
    "링크": "https://arstechnica.com/security/2026/04/microsoft-issues-emergency-update-for-macos-and-linux-asp-net-threat/",
    "수집일시": "2026-04-23T17:44:40.041512",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "Anthropic tested removing Claude Code from the Pro plan",
    "링크": "https://arstechnica.com/ai/2026/04/anthropic-tested-removing-claude-code-from-the-pro-plan/",
    "수집일시": "2026-04-23T17:44:40.041572",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "Coyote vs. Acme is finally getting released—with a killer trailer",
    "링크": "https://arstechnica.com/culture/2026/04/coyote-vs-acme-is-finally-getting-released-with-a-killer-trailer/",
    "수집일시": "2026-04-23T17:44:40.041641",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "Google unveils two new TPUs designed for the \"agentic era\"",
    "링크": "https://arstechnica.com/ai/2026/04/google-unveils-two-new-tpus-designed-for-the-agentic-era/",
    "수집일시": "2026-04-23T17:44:40.041697",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "OpenAI Blog",
    "제목": "Making ChatGPT better for clinicians",
    "링크": "https://openai.com/index/making-chatgpt-better-for-clinicians",
    "수집일시": "2026-04-23T17:44:42.618810",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "OpenAI Blog",
    "제목": "Workspace agents",
    "링크": "https://openai.com/academy/workspace-agents",
    "수집일시": "2026-04-23T17:44:42.618967",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "OpenAI Blog",
    "제목": "Introducing workspace agents in ChatGPT",
    "링크": "https://openai.com/index/introducing-workspace-agents-in-chatgpt",
    "수집일시": "2026-04-23T17:44:42.619131",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "OpenAI Blog",
    "제목": "Speeding up agentic workflows with WebSockets in the Responses API",
    "링크": "https://openai.com/index/speeding-up-agentic-workflows-with-websockets",
    "수집일시": "2026-04-23T17:44:42.619259",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "OpenAI Blog",
    "제목": "Introducing OpenAI Privacy Filter",
    "링크": "https://openai.com/index/introducing-openai-privacy-filter",
    "수집일시": "2026-04-23T17:44:42.619381",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "OpenAI Blog",
    "제목": "Introducing ChatGPT Images 2.0",
    "링크": "https://openai.com/index/introducing-chatgpt-images-2-0",
    "수집일시": "2026-04-23T17:44:42.619533",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "OpenAI Blog",
    "제목": "Scaling Codex to enterprises worldwide",
    "링크": "https://openai.com/index/scaling-codex-to-enterprises-worldwide",
    "수집일시": "2026-04-23T17:44:42.619656",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "OpenAI Blog",
    "제목": "OpenAI helps Hyatt advance AI among colleagues",
    "링크": "https://openai.com/index/hyatt-advances-ai-with-chatgpt-enterprise",
    "수집일시": "2026-04-23T17:44:42.619793",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "OpenAI Blog",
    "제목": "Codex for (almost) everything",
    "링크": "https://openai.com/index/codex-for-almost-everything",
    "수집일시": "2026-04-23T17:44:42.620258",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "OpenAI Blog",
    "제목": "Introducing GPT-Rosalind for life sciences research",
    "링크": "https://openai.com/index/introducing-gpt-rosalind",
    "수집일시": "2026-04-23T17:44:42.620427",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google DeepMind",
    "제목": "Partnering with industry leaders to accelerate AI transformation",
    "링크": "https://deepmind.google/blog/partnering-with-industry-leaders-to-accelerate-ai-transformation/",
    "수집일시": "2026-04-23T17:44:44.806918",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google DeepMind",
    "제목": "Gemini 3.1 Flash TTS: the next generation of expressive AI speech",
    "링크": "https://deepmind.google/blog/gemini-3-1-flash-tts-the-next-generation-of-expressive-ai-speech/",
    "수집일시": "2026-04-23T17:44:44.806960",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google DeepMind",
    "제목": "Gemini Robotics-ER 1.6: Powering real-world robotics tasks through enhanced embodied reasoning",
    "링크": "https://deepmind.google/blog/gemini-robotics-er-1-6/",
    "수집일시": "2026-04-23T17:44:44.806993",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google DeepMind",
    "제목": "Gemma 4: Byte for byte, the most capable open models",
    "링크": "https://deepmind.google/blog/gemma-4-byte-for-byte-the-most-capable-open-models/",
    "수집일시": "2026-04-23T17:44:44.807025",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google DeepMind",
    "제목": "Gemini 3.1 Flash Live: Making audio AI more natural and reliable",
    "링크": "https://deepmind.google/blog/gemini-3-1-flash-live-making-audio-ai-more-natural-and-reliable/",
    "수집일시": "2026-04-23T17:44:44.807073",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google DeepMind",
    "제목": "Protecting people from harmful manipulation",
    "링크": "https://deepmind.google/blog/protecting-people-from-harmful-manipulation/",
    "수집일시": "2026-04-23T17:44:44.807136",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google DeepMind",
    "제목": "Lyria 3 Pro: Create longer tracks in more",
    "링크": "https://deepmind.google/blog/lyria-3-pro-create-longer-tracks-in-more/",
    "수집일시": "2026-04-23T17:44:44.807197",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google DeepMind",
    "제목": "Measuring progress toward AGI: A cognitive framework",
    "링크": "https://deepmind.google/blog/measuring-progress-toward-agi-a-cognitive-framework/",
    "수집일시": "2026-04-23T17:44:44.807257",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google DeepMind",
    "제목": "From games to biology and beyond: 10 years of AlphaGo’s impact",
    "링크": "https://deepmind.google/blog/10-years-of-alphago/",
    "수집일시": "2026-04-23T17:44:44.807290",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google DeepMind",
    "제목": "Gemini 3.1 Flash-Lite: Built for intelligence at scale",
    "링크": "https://deepmind.google/blog/gemini-3-1-flash-lite-built-for-intelligence-at-scale/",
    "수집일시": "2026-04-23T17:44:44.807344",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google Research",
    "제목": "It's all about the angle: Your photos, re-composed",
    "링크": "https://research.google/blog/its-all-about-the-angle-your-photos-re-composed/",
    "수집일시": "2026-04-23T17:44:47.189950",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google Research",
    "제목": "ReasoningBank: Enabling agents to learn from experience",
    "링크": "https://research.google/blog/reasoningbank-enabling-agents-to-learn-from-experience/",
    "수집일시": "2026-04-23T17:44:47.190111",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google Research",
    "제목": "Designing synthetic datasets for the real world: Mechanism design and reasoning from first principles",
    "링크": "https://research.google/blog/designing-synthetic-datasets-for-the-real-world-mechanism-design-and-reasoning-from-first-principles/",
    "수집일시": "2026-04-23T17:44:47.190279",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google Research",
    "제목": "AI-generated synthetic neurons speed up brain mapping",
    "링크": "https://research.google/blog/ai-generated-synthetic-neurons-speed-up-brain-mapping/",
    "수집일시": "2026-04-23T17:44:47.190381",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google Research",
    "제목": "Towards developing future-ready skills with generative AI",
    "링크": "https://research.google/blog/towards-developing-future-ready-skills-with-generative-ai/",
    "수집일시": "2026-04-23T17:44:47.190478",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google Research",
    "제목": "ConvApparel: Measuring and bridging the realism gap in user simulators",
    "링크": "https://research.google/blog/convapparel-measuring-and-bridging-the-realism-gap-in-user-simulators/",
    "수집일시": "2026-04-23T17:44:47.190572",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google Research",
    "제목": "Improving the academic workflow: Introducing two AI agents for better figures and peer review",
    "링크": "https://research.google/blog/improving-the-academic-workflow-introducing-two-ai-agents-for-better-figures-and-peer-review/",
    "수집일시": "2026-04-23T17:44:47.190664",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google Research",
    "제목": "Evaluating alignment of behavioral dispositions in LLMs",
    "링크": "https://research.google/blog/evaluating-alignment-of-behavioral-dispositions-in-llms/",
    "수집일시": "2026-04-23T17:44:47.190783",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google Research",
    "제목": "Building better AI benchmarks: How many raters are enough?",
    "링크": "https://research.google/blog/building-better-ai-benchmarks-how-many-raters-are-enough/",
    "수집일시": "2026-04-23T17:44:47.190883",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Google Research",
    "제목": "Safeguarding cryptocurrency by disclosing quantum vulnerabilities responsibly",
    "링크": "https://research.google/blog/safeguarding-cryptocurrency-by-disclosing-quantum-vulnerabilities-responsibly/",
    "수집일시": "2026-04-23T17:44:47.190984",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Microsoft Research",
    "제목": "AutoAdapt: Automated domain adaptation for large language models",
    "링크": "https://www.microsoft.com/en-us/research/blog/autoadapt-automated-domain-adaptation-for-large-language-models/",
    "수집일시": "2026-04-23T17:44:49.489226",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Microsoft Research",
    "제목": "Can we AI our way to a more sustainable world?",
    "링크": "https://www.microsoft.com/en-us/research/podcast/can-we-ai-our-way-to-a-more-sustainable-world/",
    "수집일시": "2026-04-23T17:44:49.489296",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Microsoft Research",
    "제목": "New Future of Work: AI is driving rapid change, uneven benefits",
    "링크": "https://www.microsoft.com/en-us/research/blog/new-future-of-work-ai-is-driving-rapid-change-uneven-benefits/",
    "수집일시": "2026-04-23T17:44:49.489355",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Microsoft Research",
    "제목": "Ideas: Steering AI toward the work future we want",
    "링크": "https://www.microsoft.com/en-us/research/podcast/ideas-steering-ai-toward-the-work-future-we-want/",
    "수집일시": "2026-04-23T17:44:49.489411",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Microsoft Research",
    "제목": "ADeLe: Predicting and explaining AI performance across tasks",
    "링크": "https://www.microsoft.com/en-us/research/blog/adele-predicting-and-explaining-ai-performance-across-tasks/",
    "수집일시": "2026-04-23T17:44:49.489468",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Microsoft Research",
    "제목": "AsgardBench: A benchmark for visually grounded interactive planning",
    "링크": "https://www.microsoft.com/en-us/research/blog/asgardbench-a-benchmark-for-visually-grounded-interactive-planning/",
    "수집일시": "2026-04-23T17:44:49.489524",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Microsoft Research",
    "제목": "GroundedPlanBench: Spatially grounded long-horizon task planning for robot manipulation",
    "링크": "https://www.microsoft.com/en-us/research/blog/groundedplanbench-spatially-grounded-long-horizon-task-planning-for-robot-manipulation/",
    "수집일시": "2026-04-23T17:44:49.489581",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Microsoft Research",
    "제목": "Will machines ever be intelligent?",
    "링크": "https://www.microsoft.com/en-us/research/podcast/will-machines-ever-be-intelligent/",
    "수집일시": "2026-04-23T17:44:49.489639",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Microsoft Research",
    "제목": "Systematic debugging for AI agents: Introducing the AgentRx framework",
    "링크": "https://www.microsoft.com/en-us/research/blog/systematic-debugging-for-ai-agents-introducing-the-agentrx-framework/",
    "수집일시": "2026-04-23T17:44:49.489701",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Microsoft Research",
    "제목": "PlugMem: Transforming raw agent interactions into reusable knowledge",
    "링크": "https://www.microsoft.com/en-us/research/blog/from-raw-interaction-to-reusable-knowledge-rethinking-memory-for-ai-agents/",
    "수집일시": "2026-04-23T17:44:49.489757",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "MIT Tech Review AI",
    "제목": "The Download: introducing the 10 Things That Matter in AI Right Now",
    "링크": "https://www.technologyreview.com/2026/04/22/1136310/the-download-10-things-that-matter-in-ai-right-now/",
    "수집일시": "2026-04-23T17:44:51.843815",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "MIT Tech Review AI",
    "제목": "AI needs a strong data fabric to deliver business value",
    "링크": "https://www.technologyreview.com/2026/04/22/1135295/ai-needs-a-strong-data-fabric-to-deliver-business-value/",
    "수집일시": "2026-04-23T17:44:51.844000",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "MIT Tech Review AI",
    "제목": "3 things Michelle Kim is into right now",
    "링크": "https://www.technologyreview.com/2026/04/22/1135423/3-things-michelle-kim/",
    "수집일시": "2026-04-23T17:44:51.844131",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "MIT Tech Review AI",
    "제목": "One town’s scheme to get rid of its geese",
    "링크": "https://www.technologyreview.com/2026/04/22/1135430/california-town-scheme-get-rid-geese/",
    "수집일시": "2026-04-23T17:44:51.844275",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "MIT Tech Review AI",
    "제목": "There is no nature anymore",
    "링크": "https://www.technologyreview.com/2026/04/22/1135440/editors-letter-may-2026/",
    "수집일시": "2026-04-23T17:44:51.844335",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "MIT Tech Review AI",
    "제목": "Los Angeles is finally going underground",
    "링크": "https://www.technologyreview.com/2026/04/22/1135449/los-angeles-subway-going-underground/",
    "수집일시": "2026-04-23T17:44:51.844389",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "MIT Tech Review AI",
    "제목": "Roundtables: Unveiling The 10 Things That Matter in AI Right Now",
    "링크": "https://www.technologyreview.com/2026/04/21/1135486/roundtables-unveiling-the-10-things-that-matter-in-ai-right-now/",
    "수집일시": "2026-04-23T17:44:51.844449",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "MIT Tech Review AI",
    "제목": "The new word in home construction could be “plastics”",
    "링크": "https://www.technologyreview.com/2026/04/21/1134856/the-new-word-in-home-construction-could-be-plastics/",
    "수집일시": "2026-04-23T17:44:51.844567",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "MIT Tech Review AI",
    "제목": "A natural protein may protect the GI tract from infection",
    "링크": "https://www.technologyreview.com/2026/04/21/1134858/a-natural-protein-may-protect-the-gi-tract-from-infection/",
    "수집일시": "2026-04-23T17:44:51.844643",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "MIT Tech Review AI",
    "제목": "This tool could show how consciousness works",
    "링크": "https://www.technologyreview.com/2026/04/21/1134862/this-tool-could-show-how-consciousness-works/",
    "수집일시": "2026-04-23T17:44:51.844720",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "VentureBeat AI",
    "제목": "OpenAI unveils Workspace Agents, a successor to custom GPTs for enterprises that can plug directly into Slack, Salesforce and more",
    "링크": "https://venturebeat.com/orchestration/openai-unveils-workspace-agents-a-successor-to-custom-gpts-for-enterprises-that-can-plug-directly-into-slack-salesforce-and-more",
    "수집일시": "2026-04-23T17:44:52.905463",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "VentureBeat AI",
    "제목": "Google and AWS split the AI agent stack between control and execution",
    "링크": "https://venturebeat.com/orchestration/google-and-aws-split-the-ai-agent-stack-between-control-and-execution",
    "수집일시": "2026-04-23T17:44:52.905561",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "VentureBeat AI",
    "제목": "Are you paying an AI ‘swarm tax’? Why single agents often beat complex systems",
    "링크": "https://venturebeat.com/orchestration/are-you-paying-an-ai-swarm-tax-why-single-agents-often-beat-complex-systems",
    "수집일시": "2026-04-23T17:44:52.905631",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "VentureBeat AI",
    "제목": "OpenAI launches Privacy Filter, an open source, on-device data sanitization model that removes personal information from enterprise datasets",
    "링크": "https://venturebeat.com/data/openai-launches-privacy-filter-an-open-source-on-device-data-sanitization-model-that-removes-personal-information-from-enterprise-datasets",
    "수집일시": "2026-04-23T17:44:52.905703",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "VentureBeat AI",
    "제목": "Google doesn't pay the Nvidia tax. Its new TPUs explain why.",
    "링크": "https://venturebeat.com/orchestration/google-doesnt-pay-the-nvidia-tax-its-new-tpus-explain-why",
    "수집일시": "2026-04-23T17:44:52.905789",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "VentureBeat AI",
    "제목": "Salesforce’s Agentforce Vibes 2.0 targets a hidden failure: context overload in AI agents",
    "링크": "https://venturebeat.com/orchestration/salesforces-agentforce-vibes-2-0-targets-a-hidden-failure-context-overload-in-ai-agents",
    "수집일시": "2026-04-23T17:44:52.905861",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "VentureBeat AI",
    "제목": "Google’s Gemini can now run on a single air-gapped server — and vanish when you pull the plug",
    "링크": "https://venturebeat.com/technology/googles-gemini-can-now-run-on-a-single-air-gapped-server-and-vanish-when-you-pull-the-plug",
    "수집일시": "2026-04-23T17:44:52.905939",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The AI Blog (MS)",
    "제목": "A conversation with Kevin Scott: What’s next in AI",
    "링크": "https://blogs.microsoft.com/ai/a-conversation-with-kevin-scott-whats-next-in-ai/",
    "수집일시": "2026-04-23T17:44:54.154507",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The AI Blog (MS)",
    "제목": "From Hot Wheels to handling content: How brands are using Microsoft AI to be more productive and imaginative",
    "링크": "https://blogs.microsoft.com/ai/from-hot-wheels-to-handling-content-how-brands-are-using-microsoft-ai-to-be-more-productive-and-imaginative/",
    "수집일시": "2026-04-23T17:44:54.154622",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The AI Blog (MS)",
    "제목": "Microsoft open sources its ‘farm of the future’ toolkit",
    "링크": "https://blogs.microsoft.com/ai/microsoft-open-sources-its-farm-of-the-future-toolkit/",
    "수집일시": "2026-04-23T17:44:54.154706",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The AI Blog (MS)",
    "제목": "How data and AI will transform contact centres for financial services",
    "링크": "https://cloudblogs.microsoft.com/industry-blog/en-gb/financial-services/2022/07/25/how-data-and-ai-will-transform-contact-centres-for-financial-services/",
    "수집일시": "2026-04-23T17:44:54.154769",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The AI Blog (MS)",
    "제목": "AI-equipped drones study dolphins on the edge of extinction",
    "링크": "https://news.microsoft.com/apac/features/ai-drones-dolphins-maui63/",
    "수집일시": "2026-04-23T17:44:54.154832",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The AI Blog (MS)",
    "제목": "Online math tutoring service uses AI to help boost students’ skills and confidence",
    "링크": "https://blogs.microsoft.com/ai/eedi-online-math-quiz/",
    "수집일시": "2026-04-23T17:44:54.154892",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The AI Blog (MS)",
    "제목": "AI-Mimi is building inclusive TV experiences for Deaf and Hard of Hearing user in Japan",
    "링크": "https://blogs.microsoft.com/accessibility/ai-mimi-is-building-inclusive-tv-experiences-for-deaf-and-hard-of-hearing-user-in-japan/",
    "수집일시": "2026-04-23T17:44:54.154951",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The AI Blog (MS)",
    "제목": "Microsoft’s framework for building AI systems responsibly",
    "링크": "https://blogs.microsoft.com/on-the-issues/2022/06/21/microsofts-framework-for-building-ai-systems-responsibly/",
    "수집일시": "2026-04-23T17:44:54.155011",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The AI Blog (MS)",
    "제목": "Singapore develops Asia’s first AI-based mobile app for shark and ray fin identification to combat illegal wildlife trade",
    "링크": "https://news.microsoft.com/en-sg/2022/06/08/singapore-develops-asias-first-ai-based-mobile-app-for-shark-and-ray-fin-identification-to-combat-illegal-wildlife-trade/",
    "수집일시": "2026-04-23T17:44:54.155087",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "The AI Blog (MS)",
    "제목": "The opportunity at home – can AI drive innovation in personal assistant devices and sign language?",
    "링크": "https://blogs.microsoft.com/accessibility/the-opportunity-at-home-can-ai-drive-innovation-in-personal-assistant-devices-and-sign-language/",
    "수집일시": "2026-04-23T17:44:54.155153",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "부산일보",
    "제목": "삼성SDS, 구글 클라우드와 손잡고 AI·클라우드 공략",
    "링크": "https://n.news.naver.com/mnews/article/082/0001377446",
    "요약": "삼성SDS가 세계적인 기술 기업 구글 클라우드와 힘을 합쳐 글로벌 인공지능(AI)과 클라우드 시장 공략을 본격화합니다. 양사는 보안 기술을 강화하고 기업들이 더 쉽고 효율적으로 AI 서비스를 이용할 수 있는 미래형 디지털 환경을 함께 만들어갈 예정입니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/082/2026/04/23/1377446.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:29:06.113252",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "부산일보",
    "title": "삼성SDS, 구글 클라우드와 손잡고 AI·클라우드 공략",
    "link": "https://n.news.naver.com/mnews/article/082/0001377446",
    "summary": "삼성SDS가 세계적인 기술 기업 구글 클라우드와 힘을 합쳐 글로벌 인공지능(AI)과 클라우드 시장 공략을 본격화합니다. 양사는 보안 기술을 강화하고 기업들이 더 쉽고 효율적으로 AI 서비스를 이용할 수 있는 미래형 디지털 환경을 함께 만들어갈 예정입니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/082/2026/04/23/1377446.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:29:06.113252",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "YTN",
    "제목": "日 소니, 탁구 AI로봇 개발 \"전국대회 출전 선수 이겨\"",
    "링크": "https://n.news.naver.com/mnews/article/052/0002344673",
    "요약": "소니가 전국대회 수준의 숙련된 선수까지 꺾을 수 있는 고성능 탁구 로봇 '에이스'를 선보였습니다. 인공지능이 선수의 움직임을 정밀하게 분석해 대응하는 기술을 갖춘 것으로, 단순한 동작 반복을 넘어 스포츠 영역에서도 인간의 능력을 추월하기 시작했음을 보여줍니다. 로봇과 인간이 스포츠로 진검승부를 벌이는 영화 같은 장면이 이제 현실이 되었습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/052/2026/04/23/2344673.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:29:06.113252",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "YTN",
    "title": "日 소니, 탁구 AI로봇 개발 \"전국대회 출전 선수 이겨\"",
    "link": "https://n.news.naver.com/mnews/article/052/0002344673",
    "summary": "소니가 전국대회 수준의 숙련된 선수까지 꺾을 수 있는 고성능 탁구 로봇 '에이스'를 선보였습니다. 인공지능이 선수의 움직임을 정밀하게 분석해 대응하는 기술을 갖춘 것으로, 단순한 동작 반복을 넘어 스포츠 영역에서도 인간의 능력을 추월하기 시작했음을 보여줍니다. 로봇과 인간이 스포츠로 진검승부를 벌이는 영화 같은 장면이 이제 현실이 되었습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/052/2026/04/23/2344673.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:29:06.113252",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "이데일리",
    "제목": "상한가 찍더니 수익률 '-25%' 날벼락…양자컴 테마주 경고등",
    "링크": "https://n.news.naver.com/mnews/article/018/0006263618",
    "요약": "최근 초고속 연산이 가능한 양자컴퓨터 기술에 대한 기대감으로 관련 주식들이 큰 관심을 받았으나, 단기 급등 이후 가격이 급격히 떨어지며 변동성이 커지고 있습니다. 실질적인 기술 성과보다는 시장의 유행에 따른 과열 양상을 보이고 있어, 투자자들의 신중한 접근과 주의가 필요한 시점입니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/018/2026/04/22/6263618.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:29:06.113252",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "이데일리",
    "title": "상한가 찍더니 수익률 '-25%' 날벼락…양자컴 테마주 경고등",
    "link": "https://n.news.naver.com/mnews/article/018/0006263618",
    "summary": "최근 초고속 연산이 가능한 양자컴퓨터 기술에 대한 기대감으로 관련 주식들이 큰 관심을 받았으나, 단기 급등 이후 가격이 급격히 떨어지며 변동성이 커지고 있습니다. 실질적인 기술 성과보다는 시장의 유행에 따른 과열 양상을 보이고 있어, 투자자들의 신중한 접근과 주의가 필요한 시점입니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/018/2026/04/22/6263618.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:29:06.113252",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "매일경제",
    "제목": "LG유플러스, 유심 업데이트·교체 100만건 돌파",
    "링크": "https://n.news.naver.com/mnews/article/009/0005670255",
    "요약": "LG유플러스가 보안 강화와 서비스 품질 향상을 위해 실시한 유심(USIM) 교체 및 업데이트 서비스가 시행 10일 만에 100만 건을 넘어섰습니다. 온·오프라인을 연계한 적극적인 지원 체계 덕분에 빠르게 확산되고 있으며, 전국적인 무료 지원은 다음 달에도 계속될 예정입니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/009/2026/04/23/5670255.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:29:06.113252",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "매일경제",
    "title": "LG유플러스, 유심 업데이트·교체 100만건 돌파",
    "link": "https://n.news.naver.com/mnews/article/009/0005670255",
    "summary": "LG유플러스가 보안 강화와 서비스 품질 향상을 위해 실시한 유심(USIM) 교체 및 업데이트 서비스가 시행 10일 만에 100만 건을 넘어섰습니다. 온·오프라인을 연계한 적극적인 지원 체계 덕분에 빠르게 확산되고 있으며, 전국적인 무료 지원은 다음 달에도 계속될 예정입니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/009/2026/04/23/5670255.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:29:06.113252",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "뉴시스",
    "제목": "KT CEO가 다시 인사·조직 '전권' 쥔다…이사회 규정 대수술",
    "링크": "https://n.news.naver.com/mnews/article/003/0013905813",
    "요약": "KT의 대표이사가 이사회의 사전 승인 없이도 조직 개편과 인사를 직접 단행할 수 있도록 경영 자율성이 대폭 강화되었습니다. 이와 함께 비위 의혹이 있는 이사의 회의 참석을 제한하는 규정도 신설되어, CEO의 실행력은 높이되 이사회의 투명성과 책임감은 더욱 엄격하게 관리할 전망입니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/003/2026/04/23/13905813.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:29:06.113252",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "뉴시스",
    "title": "KT CEO가 다시 인사·조직 '전권' 쥔다…이사회 규정 대수술",
    "link": "https://n.news.naver.com/mnews/article/003/0013905813",
    "summary": "KT의 대표이사가 이사회의 사전 승인 없이도 조직 개편과 인사를 직접 단행할 수 있도록 경영 자율성이 대폭 강화되었습니다. 이와 함께 비위 의혹이 있는 이사의 회의 참석을 제한하는 규정도 신설되어, CEO의 실행력은 높이되 이사회의 투명성과 책임감은 더욱 엄격하게 관리할 전망입니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/003/2026/04/23/13905813.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:29:06.113252",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "디지털타임스",
    "제목": "소재산업 일군 지난 50년…‘글로벌 소재혁신 리더’ 도약",
    "링크": "https://n.news.naver.com/mnews/article/029/0003023446",
    "요약": "대한민국 소재 기술의 핵심 거점인 한국재료연구원이 설립 50주년을 맞아 새로운 미래 비전을 선포했습니다. 지난 반세기 동안 쌓아온 기술력을 바탕으로, 앞으로 다가올 100년은 전 세계 소재 산업을 이끄는 혁신 리더로서 첨단 산업의 뿌리를 더욱 단단하게 다질 계획입니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/029/2026/04/23/3023446.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:29:06.113252",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "디지털타임스",
    "title": "소재산업 일군 지난 50년…‘글로벌 소재혁신 리더’ 도약",
    "link": "https://n.news.naver.com/mnews/article/029/0003023446",
    "summary": "대한민국 소재 기술의 핵심 거점인 한국재료연구원이 설립 50주년을 맞아 새로운 미래 비전을 선포했습니다. 지난 반세기 동안 쌓아온 기술력을 바탕으로, 앞으로 다가올 100년은 전 세계 소재 산업을 이끄는 혁신 리더로서 첨단 산업의 뿌리를 더욱 단단하게 다질 계획입니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/029/2026/04/23/3023446.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:29:06.113252",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "조선비즈",
    "제목": "드림에이지 ‘별이되어라2′ 6월 서비스 종료…출시 2년 만",
    "링크": "https://n.news.naver.com/mnews/article/366/0001159290",
    "요약": "액션 MORPG '별이되어라2: 베다의 기사들'이 출시 약 2년 만에 서비스를 종료한다는 안타까운 소식을 전했습니다. 화려한 그래픽으로 기대를 모았던 작품이나, 운영진은 논의 끝에 오는 6월 운영을 마무리하기로 결정했습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/366/2026/04/23/1159290.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:29:06.113252",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "조선비즈",
    "title": "드림에이지 ‘별이되어라2′ 6월 서비스 종료…출시 2년 만",
    "link": "https://n.news.naver.com/mnews/article/366/0001159290",
    "summary": "액션 MORPG '별이되어라2: 베다의 기사들'이 출시 약 2년 만에 서비스를 종료한다는 안타까운 소식을 전했습니다. 화려한 그래픽으로 기대를 모았던 작품이나, 운영진은 논의 끝에 오는 6월 운영을 마무리하기로 결정했습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/366/2026/04/23/1159290.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:29:06.113252",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "국내",
    "매체": "조선비즈",
    "제목": "‘반도체 심장’ 평택에 4만명 모인 삼성전자 노조… 생산 차질 우려 증폭",
    "링크": "https://n.news.naver.com/mnews/article/366/0001159297",
    "요약": "삼성전자의 반도체 핵심 기지인 평택캠퍼스에 약 4만 명의 노동자가 모여 성과급 체계의 투명성과 상한제 폐지를 요구하는 대규모 집회를 열었습니다. 역대급 인원이 참여한 이번 투쟁으로 인해 세계 최대 규모인 삼성의 반도체 생산 라인 운영에 차질이 빚어질 수 있다는 우려가 나오고 있습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/366/2026/04/23/1159297.jpg?type=nf220_150",
    "수집일시": "2026-04-23T17:29:06.113252",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "조선비즈",
    "title": "‘반도체 심장’ 평택에 4만명 모인 삼성전자 노조… 생산 차질 우려 증폭",
    "link": "https://n.news.naver.com/mnews/article/366/0001159297",
    "summary": "삼성전자의 반도체 핵심 기지인 평택캠퍼스에 약 4만 명의 노동자가 모여 성과급 체계의 투명성과 상한제 폐지를 요구하는 대규모 집회를 열었습니다. 역대급 인원이 참여한 이번 투쟁으로 인해 세계 최대 규모인 삼성의 반도체 생산 라인 운영에 차질이 빚어질 수 있다는 우려가 나오고 있습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/366/2026/04/23/1159297.jpg?type=nf220_150",
    "collected_at": "2026-04-23T17:29:06.113252",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success",
    "type": "article"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "AI Tools Are Helping Mediocre North Korean Hackers Steal Millions",
    "링크": "https://www.wired.com/story/ai-tools-are-helping-mediocre-north-korean-hackers-steal-millions/",
    "수집일시": "2026-04-23T17:30:11.200406",
    "type": "article"
  },
  {
    "국가": "유튜브",
    "매체": "Two Minute Papers",
    "제목": "DeepMind’s New AI: A Gift To Humanity",
    "링크": "https://www.youtube.com/watch?v=Sk9tvyRSCgY",
    "요약": "❤️ Check out Lambda here and sign up for their GPU Cloud: https://lambda.ai/papers\n\nLinks:\nhttps://deepmind.google/models/gemma/gemma-4/\nhttps://ai.google.dev/gemma/docs/core/model_card_4\n\nFine tuning...",
    "이미지": "https://img.youtube.com/vi/Sk9tvyRSCgY/maxresdefault.jpg",
    "수집일시": "2026-04-23T17:30:37.575068",
    "type": "youtube"
  }
];