window.NEWS_DATA = [
  {
    "국가": "국내",
    "매체": "머니투데이",
    "제목": "원안위, 2030년까지 원자력 안전규제 개편…\"SMR 특성 반영\"",
    "링크": "https://n.news.naver.com/mnews/article/008/0005317972",
    "요약": "정부가 차세대 에너지원으로 주목받는 소형 원자로(SMR)의 특성에 맞춰 2030년까지 새로운 안전 규제 기준을 마련합니다. 기존 대형 원전과는 다른 SMR만의 기술적 차이를 반영해 안전을 확보하면서도, 우리나라가 글로벌 원전 시장에서 기술 경쟁력을 앞서나갈 수 있도록 지원할 계획입니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/008/2026/02/12/5317972.jpg?type=nf220_150",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "머니투데이",
    "title": "원안위, 2030년까지 원자력 안전규제 개편…\"SMR 특성 반영\"",
    "link": "https://n.news.naver.com/mnews/article/008/0005317972",
    "summary": "정부가 차세대 에너지원으로 주목받는 소형 원자로(SMR)의 특성에 맞춰 2030년까지 새로운 안전 규제 기준을 마련합니다. 기존 대형 원전과는 다른 SMR만의 기술적 차이를 반영해 안전을 확보하면서도, 우리나라가 글로벌 원전 시장에서 기술 경쟁력을 앞서나갈 수 있도록 지원할 계획입니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/008/2026/02/12/5317972.jpg?type=nf220_150",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "국내",
    "매체": "SBS Biz",
    "제목": "잘 가나 싶더니 또…\"애플, 차세대 시리 '테스트 암초'\"",
    "링크": "https://n.news.naver.com/mnews/article/374/0000492491",
    "요약": "애플의 차세대 인공지능 비서 '시리'가 출시 전 최종 점검 과정에서 기술적 난관에 부딪혔습니다. 이로 인해 기대를 모았던 핵심 기능들의 도입 시기가 당초 계획보다 뒤로 밀릴 가능성이 커지고 있습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/374/2026/02/13/492491.jpg?type=nf220_150",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "SBS Biz",
    "title": "잘 가나 싶더니 또…\"애플, 차세대 시리 '테스트 암초'\"",
    "link": "https://n.news.naver.com/mnews/article/374/0000492491",
    "summary": "애플의 차세대 인공지능 비서 '시리'가 출시 전 최종 점검 과정에서 기술적 난관에 부딪혔습니다. 이로 인해 기대를 모았던 핵심 기능들의 도입 시기가 당초 계획보다 뒤로 밀릴 가능성이 커지고 있습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/374/2026/02/13/492491.jpg?type=nf220_150",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "국내",
    "매체": "매일경제",
    "제목": "크래프톤 신작 ‘프로젝트 윈드리스’ 베일 벗었다",
    "링크": "https://n.news.naver.com/mnews/article/009/0005637099",
    "요약": "인기 소설 '눈물을 마시는 새'의 독창적인 세계관을 담은 신작 게임 '프로젝트 윈드리스'가 공개되어 화제입니다. PC와 콘솔 플랫폼을 통해 출시될 이 게임은 한국형 판타지의 매력을 고품질 그래픽으로 구현해 전 세계 게이머들의 기대를 받고 있습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/009/2026/02/13/5637099.jpg?type=nf220_150",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "매일경제",
    "title": "크래프톤 신작 ‘프로젝트 윈드리스’ 베일 벗었다",
    "link": "https://n.news.naver.com/mnews/article/009/0005637099",
    "summary": "인기 소설 '눈물을 마시는 새'의 독창적인 세계관을 담은 신작 게임 '프로젝트 윈드리스'가 공개되어 화제입니다. PC와 콘솔 플랫폼을 통해 출시될 이 게임은 한국형 판타지의 매력을 고품질 그래픽으로 구현해 전 세계 게이머들의 기대를 받고 있습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/009/2026/02/13/5637099.jpg?type=nf220_150",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "국내",
    "매체": "아이뉴스24",
    "제목": "펄어비스, '붉은사막' 세번째 프리뷰 영상 공개…일상 콘텐츠 공개",
    "링크": "https://n.news.naver.com/mnews/article/031/0001005773",
    "요약": "국내 게임사 펄어비스가 신작 '붉은사막' 속 가상 세계의 생생한 일상을 담은 새로운 영상을 공개했습니다. 단순히 적과 싸우는 전투를 넘어, 드넓은 대륙을 탐험하고 다양한 삶을 체험하는 오픈월드 게임만의 다채로운 매력을 선보였습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/031/2026/02/13/1005773.jpg?type=nf220_150",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "아이뉴스24",
    "title": "펄어비스, '붉은사막' 세번째 프리뷰 영상 공개…일상 콘텐츠 공개",
    "link": "https://n.news.naver.com/mnews/article/031/0001005773",
    "summary": "국내 게임사 펄어비스가 신작 '붉은사막' 속 가상 세계의 생생한 일상을 담은 새로운 영상을 공개했습니다. 단순히 적과 싸우는 전투를 넘어, 드넓은 대륙을 탐험하고 다양한 삶을 체험하는 오픈월드 게임만의 다채로운 매력을 선보였습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/031/2026/02/13/1005773.jpg?type=nf220_150",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "국내",
    "매체": "지디넷코리아",
    "제목": "KT \"광화문 스크린에 내 작품 걸어보세요\"",
    "링크": "https://n.news.naver.com/mnews/article/092/0002410641",
    "요약": "KT가 광화문 빌딩의 초대형 미디어 스크린을 시민들의 예술 작품으로 채우는 특별한 공모전을 개최합니다. 전공에 상관없이 누구나 자신의 상상력을 디지털 예술로 구현해 도심 한복판 대형 화면에 직접 전시할 수 있는 기회입니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/092/2026/02/13/2410641.jpg?type=nf220_150",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "지디넷코리아",
    "title": "KT \"광화문 스크린에 내 작품 걸어보세요\"",
    "link": "https://n.news.naver.com/mnews/article/092/0002410641",
    "summary": "KT가 광화문 빌딩의 초대형 미디어 스크린을 시민들의 예술 작품으로 채우는 특별한 공모전을 개최합니다. 전공에 상관없이 누구나 자신의 상상력을 디지털 예술로 구현해 도심 한복판 대형 화면에 직접 전시할 수 있는 기회입니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/092/2026/02/13/2410641.jpg?type=nf220_150",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "국내",
    "매체": "이데일리",
    "제목": "kt밀리의서재, 연매출 882억 영업이익 144억… 창립 이래 최대",
    "링크": "https://n.news.naver.com/mnews/article/018/0006218981",
    "요약": "국내 대표 독서 플랫폼인 밀리의서재가 2025년 매출 882억 원을 돌파하며 창사 이래 최고의 성적표를 받아 들었습니다. 영업이익 또한 144억 원으로 역대 최대치를 기록하며, 디지털 콘텐츠 시장 내 압도적인 성장세를 입증했습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/018/2026/02/13/6218981.jpg?type=nf220_150",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "이데일리",
    "title": "kt밀리의서재, 연매출 882억 영업이익 144억… 창립 이래 최대",
    "link": "https://n.news.naver.com/mnews/article/018/0006218981",
    "summary": "국내 대표 독서 플랫폼인 밀리의서재가 2025년 매출 882억 원을 돌파하며 창사 이래 최고의 성적표를 받아 들었습니다. 영업이익 또한 144억 원으로 역대 최대치를 기록하며, 디지털 콘텐츠 시장 내 압도적인 성장세를 입증했습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/018/2026/02/13/6218981.jpg?type=nf220_150",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "국내",
    "매체": "아시아경제",
    "제목": "전 세계 랜드마크 등장한 갓 쓴 호랑이…삼성, 갤럭시 언팩 3D 옥외광고",
    "링크": "https://n.news.naver.com/mnews/article/277/0005721717",
    "요약": "삼성전자가 전 세계 17개국 주요 명소에서 인공지능(AI) 기술을 탑재한 새로운 갤럭시 기기를 알리는 대형 3D 옥외광고를 시작했습니다. 전통 갓을 쓴 호랑이가 화면 밖으로 튀어나올 듯한 생생한 입체 영상을 통해 전 세계에 한국의 미와 진화된 기술력을 동시에 선보이고 있습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/277/2026/02/13/5721717.jpg?type=nf220_150",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "아시아경제",
    "title": "전 세계 랜드마크 등장한 갓 쓴 호랑이…삼성, 갤럭시 언팩 3D 옥외광고",
    "link": "https://n.news.naver.com/mnews/article/277/0005721717",
    "summary": "삼성전자가 전 세계 17개국 주요 명소에서 인공지능(AI) 기술을 탑재한 새로운 갤럭시 기기를 알리는 대형 3D 옥외광고를 시작했습니다. 전통 갓을 쓴 호랑이가 화면 밖으로 튀어나올 듯한 생생한 입체 영상을 통해 전 세계에 한국의 미와 진화된 기술력을 동시에 선보이고 있습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/277/2026/02/13/5721717.jpg?type=nf220_150",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "국내",
    "매체": "뉴시스",
    "제목": "트릴리온랩스, '국대 AI' 패자부활전 참가…포스코·GS 합류",
    "링크": "https://n.news.naver.com/mnews/article/003/0013768955",
    "요약": "국내 스타트업 트릴리온랩스가 포스코, GS와 같은 대기업들과 힘을 합쳐 한국 대표 인공지능 개발을 위한 재도전에 나섰습니다. 민간 기업의 강력한 협업을 통해 우리만의 독자적인 AI 기술을 완성하고 국가 경쟁력을 높인다는 구상입니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/003/2026/02/13/13768955.jpg?type=nf220_150",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "뉴시스",
    "title": "트릴리온랩스, '국대 AI' 패자부활전 참가…포스코·GS 합류",
    "link": "https://n.news.naver.com/mnews/article/003/0013768955",
    "summary": "국내 스타트업 트릴리온랩스가 포스코, GS와 같은 대기업들과 힘을 합쳐 한국 대표 인공지능 개발을 위한 재도전에 나섰습니다. 민간 기업의 강력한 협업을 통해 우리만의 독자적인 AI 기술을 완성하고 국가 경쟁력을 높인다는 구상입니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/003/2026/02/13/13768955.jpg?type=nf220_150",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "국내",
    "매체": "뉴시스",
    "제목": "갤럭시 S26 들어갈 엑시노스 vs 스냅드래곤, AI 성능 테스트해보니",
    "링크": "https://n.news.naver.com/mnews/article/003/0013769112",
    "요약": "삼성전자가 개발 중인 차세대 스마트폰 두뇌 '엑시노스 2600'이 인공지능(AI) 성능 대결에서 강력한 라이벌인 퀄컴을 앞질렀다는 반가운 소식입니다. 이 칩셋들이 탑재될 갤럭시 S26은 지금보다 훨씬 더 똑똑하고 복잡한 작업을 척척 해내는 진정한 AI 폰으로 거듭날 전망입니다. 세계 최고의 기술력을 다투는 두 반도체 칩의 흥미진진한 경쟁 덕분에 미래 스마트폰의 진화가 더욱 기대됩니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/003/2026/02/13/13769112.jpg?type=nf220_150",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "뉴시스",
    "title": "갤럭시 S26 들어갈 엑시노스 vs 스냅드래곤, AI 성능 테스트해보니",
    "link": "https://n.news.naver.com/mnews/article/003/0013769112",
    "summary": "삼성전자가 개발 중인 차세대 스마트폰 두뇌 '엑시노스 2600'이 인공지능(AI) 성능 대결에서 강력한 라이벌인 퀄컴을 앞질렀다는 반가운 소식입니다. 이 칩셋들이 탑재될 갤럭시 S26은 지금보다 훨씬 더 똑똑하고 복잡한 작업을 척척 해내는 진정한 AI 폰으로 거듭날 전망입니다. 세계 최고의 기술력을 다투는 두 반도체 칩의 흥미진진한 경쟁 덕분에 미래 스마트폰의 진화가 더욱 기대됩니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/003/2026/02/13/13769112.jpg?type=nf220_150",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "국내",
    "매체": "디지털데일리",
    "제목": "\"내부 위기설 사실무근\"…애플, 차세대 시리 지연 공식 반박",
    "링크": "https://n.news.naver.com/mnews/article/138/0002218067",
    "요약": "애플이 차세대 인공지능 '시리'의 개발이 늦어지고 있다는 최근의 소문을 공식적으로 부인하며 예정대로 올해 출시될 것임을 강조했습니다. 기술적 결함으로 인한 내부 위기설은 사실이 아니라고 선을 그으며, 한층 똑똑해진 AI 비서의 등장을 예고했습니다.",
    "이미지": "https://mimgnews.pstatic.net/image/origin/138/2026/02/13/2218067.jpg?type=nf220_150",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "original-source-image",
    "이미지생성방식": "source-original",
    "country": "domestic",
    "media": "디지털데일리",
    "title": "\"내부 위기설 사실무근\"…애플, 차세대 시리 지연 공식 반박",
    "link": "https://n.news.naver.com/mnews/article/138/0002218067",
    "summary": "애플이 차세대 인공지능 '시리'의 개발이 늦어지고 있다는 최근의 소문을 공식적으로 부인하며 예정대로 올해 출시될 것임을 강조했습니다. 기술적 결함으로 인한 내부 위기설은 사실이 아니라고 선을 그으며, 한층 똑똑해진 AI 비서의 등장을 예고했습니다.",
    "image": "https://mimgnews.pstatic.net/image/origin/138/2026/02/13/2218067.jpg?type=nf220_150",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "original-source-image",
    "image_provider": "source-original",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "For $1M, you can pay Bryan Johnson (or BryanAI?) to teach you how to live longer",
    "링크": "https://techcrunch.com/2026/02/12/for-1-million-you-can-pay-bryan-johnson-or-bryanai-to-teach-you-how-to-live-longer/",
    "요약": "억만장자 브라이언 존슨이 약 13억 원의 비용을 지불하면 노화를 늦추는 비법을 전수해 주는 ‘이모탈스’ 프로그램을 출시했습니다. 인류의 수명 연장에 집착해 온 그가 직접 설계한 이 초고가 과정은 인간의 생물학적 한계를 극복하려는 파격적인 시도로 주목받고 있습니다.",
    "이미지": "generated_images/for-1m-you-can-pay-bryan-johnson-or-brya-27a0c6b8b139-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:ai:ai",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "TechCrunch",
    "title": "For $1M, you can pay Bryan Johnson (or BryanAI?) to teach you how to live longer",
    "link": "https://techcrunch.com/2026/02/12/for-1-million-you-can-pay-bryan-johnson-or-bryanai-to-teach-you-how-to-live-longer/",
    "summary": "억만장자 브라이언 존슨이 약 13억 원의 비용을 지불하면 노화를 늦추는 비법을 전수해 주는 ‘이모탈스’ 프로그램을 출시했습니다. 인류의 수명 연장에 집착해 온 그가 직접 설계한 이 초고가 과정은 인간의 생물학적 한계를 극복하려는 파격적인 시도로 주목받고 있습니다.",
    "image": "generated_images/for-1m-you-can-pay-bryan-johnson-or-brya-27a0c6b8b139-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:ai:ai",
    "image_provider": "simple-illustration",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "Amid disappointing earnings, Pinterest claims it sees more searches than ChatGPT",
    "링크": "https://techcrunch.com/2026/02/12/amid-disappointing-earnings-pinterest-claims-it-sees-more-searches-than-chatgpt/",
    "요약": "최근 핀터레스트가 실적 부진으로 어려움을 겪고 있지만, 서비스 이용량만큼은 여전히 높은 수준을 유지하고 있습니다. 특히 시각적 탐색 분야의 강점을 내세우며, 자사 플랫폼 내 검색량이 인공지능 열풍을 일으킨 챗GPT보다 더 많다는 점을 강조했습니다.",
    "이미지": "company_images/openai/auto-77d1369fd87f81.png",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "company-searched-pool:openai:chatgpt:v6",
    "이미지생성방식": "company-searched-image-pool",
    "country": "global",
    "media": "TechCrunch",
    "title": "Amid disappointing earnings, Pinterest claims it sees more searches than ChatGPT",
    "link": "https://techcrunch.com/2026/02/12/amid-disappointing-earnings-pinterest-claims-it-sees-more-searches-than-chatgpt/",
    "summary": "최근 핀터레스트가 실적 부진으로 어려움을 겪고 있지만, 서비스 이용량만큼은 여전히 높은 수준을 유지하고 있습니다. 특히 시각적 탐색 분야의 강점을 내세우며, 자사 플랫폼 내 검색량이 인공지능 열풍을 일으킨 챗GPT보다 더 많다는 점을 강조했습니다.",
    "image": "company_images/openai/auto-77d1369fd87f81.png",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "company-searched-pool:openai:chatgpt:v6",
    "image_provider": "company-searched-image-pool",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "IBM will hire your entry-level talent in the age of AI",
    "링크": "https://techcrunch.com/2026/02/12/ibm-will-hire-your-entry-level-talent-in-the-age-of-ai/",
    "요약": "IBM이 2026년까지 미국의 신입 사원 채용 규모를 현재보다 3배나 늘리며 공격적인 인재 확보에 나섭니다. 단순히 인원만 늘리는 것이 아니라, AI 기술 발전에 발맞춰 과거와는 완전히 다른 새로운 형태의 업무를 맡기게 될 예정입니다. 이는 AI 시대를 맞아 기업이 요구하는 실무 역량과 일자리 구조가 근본적으로 변화하고 있음을 시사합니다.",
    "이미지": "company_images/ibm/auto-3283f3b46390ee.png",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "company-searched-pool:ibm:ibm:v2",
    "이미지생성방식": "company-searched-image-pool",
    "country": "global",
    "media": "TechCrunch",
    "title": "IBM will hire your entry-level talent in the age of AI",
    "link": "https://techcrunch.com/2026/02/12/ibm-will-hire-your-entry-level-talent-in-the-age-of-ai/",
    "summary": "IBM이 2026년까지 미국의 신입 사원 채용 규모를 현재보다 3배나 늘리며 공격적인 인재 확보에 나섭니다. 단순히 인원만 늘리는 것이 아니라, AI 기술 발전에 발맞춰 과거와는 완전히 다른 새로운 형태의 업무를 맡기게 될 예정입니다. 이는 AI 시대를 맞아 기업이 요구하는 실무 역량과 일자리 구조가 근본적으로 변화하고 있음을 시사합니다.",
    "image": "company_images/ibm/auto-3283f3b46390ee.png",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "company-searched-pool:ibm:ibm:v2",
    "image_provider": "company-searched-image-pool",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "Rivian was saved by software in 2025",
    "링크": "https://techcrunch.com/2026/02/12/rivian-was-saved-by-software-in-2025/",
    "요약": "전기차 제조사 리비안이 자동차 생산을 넘어선 독보적인 소프트웨어 기술력으로 2025년 화려한 재기에 성공했습니다. 특히 폭스바겐과의 기술 협력을 통해 수익 구조를 획기적으로 개선하며, 미래 자동차 시장의 핵심 경쟁력이 하드웨어가 아닌 소프트웨어에 있음을 증명했습니다.",
    "이미지": "generated_images/rivian-was-saved-by-software-in-2025-fa0cf97a682d-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:general:none",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "TechCrunch",
    "title": "Rivian was saved by software in 2025",
    "link": "https://techcrunch.com/2026/02/12/rivian-was-saved-by-software-in-2025/",
    "summary": "전기차 제조사 리비안이 자동차 생산을 넘어선 독보적인 소프트웨어 기술력으로 2025년 화려한 재기에 성공했습니다. 특히 폭스바겐과의 기술 협력을 통해 수익 구조를 획기적으로 개선하며, 미래 자동차 시장의 핵심 경쟁력이 하드웨어가 아닌 소프트웨어에 있음을 증명했습니다.",
    "image": "generated_images/rivian-was-saved-by-software-in-2025-fa0cf97a682d-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:general:none",
    "image_provider": "simple-illustration",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "Musk needed a new vision for SpaceX and xAI. He landed on Moonbase Alpha.",
    "링크": "https://techcrunch.com/2026/02/12/musk-needed-a-new-vision-for-spacex-and-xai-he-landed-on-moonbase-alpha/",
    "요약": "일론 머스크가 달 표면에 거대한 전자기 발사대를 세워 AI 위성을 우주 멀리 쏘아 올리겠다는 파격적인 구상을 내놓았습니다. 이는 지구를 넘어 달을 본격적인 우주 탐사의 전초 기지로 삼아 인류의 활동 영역을 심우주까지 확장하려는 대담한 시도입니다.",
    "이미지": "company_images/xai/auto-48d90a08253459.png",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "company-searched-pool:xai:xai:v5",
    "이미지생성방식": "company-searched-image-pool",
    "country": "global",
    "media": "TechCrunch",
    "title": "Musk needed a new vision for SpaceX and xAI. He landed on Moonbase Alpha.",
    "link": "https://techcrunch.com/2026/02/12/musk-needed-a-new-vision-for-spacex-and-xai-he-landed-on-moonbase-alpha/",
    "summary": "일론 머스크가 달 표면에 거대한 전자기 발사대를 세워 AI 위성을 우주 멀리 쏘아 올리겠다는 파격적인 구상을 내놓았습니다. 이는 지구를 넘어 달을 본격적인 우주 탐사의 전초 기지로 삼아 인류의 활동 영역을 심우주까지 확장하려는 대담한 시도입니다.",
    "image": "company_images/xai/auto-48d90a08253459.png",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "company-searched-pool:xai:xai:v5",
    "image_provider": "company-searched-image-pool",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "Didero lands $30M to put manufacturing procurement on ‘agentic’ autopilot",
    "링크": "https://techcrunch.com/2026/02/12/didero-lands-30m-to-put-manufacturing-procurement-on-agentic-autopilot/",
    "요약": "제조 기업의 복잡한 자재 구매 업무를 스스로 판단해 처리하는 인공지능 비서 서비스 '디데로'가 대규모 투자 유치에 성공했습니다. 이 AI는 기존 기업 관리 시스템과 연동되어 이메일 확인부터 데이터 업데이트까지 복잡한 과정을 자동으로 수행합니다. 사람이 일일이 입력하지 않아도 공장 운영이 멈추지 않도록 돕는 '자율 주행형 업무 도구'인 셈입니다.",
    "이미지": "generated_images/didero-lands-30m-to-put-manufacturing-pr-22a30a3a15d0-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:ai:agent",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "TechCrunch",
    "title": "Didero lands $30M to put manufacturing procurement on ‘agentic’ autopilot",
    "link": "https://techcrunch.com/2026/02/12/didero-lands-30m-to-put-manufacturing-procurement-on-agentic-autopilot/",
    "summary": "제조 기업의 복잡한 자재 구매 업무를 스스로 판단해 처리하는 인공지능 비서 서비스 '디데로'가 대규모 투자 유치에 성공했습니다. 이 AI는 기존 기업 관리 시스템과 연동되어 이메일 확인부터 데이터 업데이트까지 복잡한 과정을 자동으로 수행합니다. 사람이 일일이 입력하지 않아도 공장 운영이 멈추지 않도록 돕는 '자율 주행형 업무 도구'인 셈입니다.",
    "image": "generated_images/didero-lands-30m-to-put-manufacturing-pr-22a30a3a15d0-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:ai:agent",
    "image_provider": "simple-illustration",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "Anthropic raises another $30B in Series G, with a new value of $380B",
    "링크": "https://techcrunch.com/2026/02/12/anthropic-raises-another-30-billion-in-series-g-with-a-new-value-of-380-billion/",
    "요약": "챗GPT의 강력한 라이벌로 꼽히는 AI 기업 앤스로픽이 약 40조 원 규모의 대규모 투자를 받으며 기업 가치가 500조 원에 육박하게 되었습니다. 이번 자금 수혈을 통해 앤스로픽은 인공지능 시장의 주도권을 잡기 위해 오픈AI와의 치열한 경쟁에 더욱 박차를 가할 것으로 보입니다.",
    "이미지": "company_images/anthropic/auto-e1fd44495c5890.png",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "company-searched-pool:anthropic:anthropic:v10",
    "이미지생성방식": "company-searched-image-pool",
    "country": "global",
    "media": "TechCrunch",
    "title": "Anthropic raises another $30B in Series G, with a new value of $380B",
    "link": "https://techcrunch.com/2026/02/12/anthropic-raises-another-30-billion-in-series-g-with-a-new-value-of-380-billion/",
    "summary": "챗GPT의 강력한 라이벌로 꼽히는 AI 기업 앤스로픽이 약 40조 원 규모의 대규모 투자를 받으며 기업 가치가 500조 원에 육박하게 되었습니다. 이번 자금 수혈을 통해 앤스로픽은 인공지능 시장의 주도권을 잡기 위해 오픈AI와의 치열한 경쟁에 더욱 박차를 가할 것으로 보입니다.",
    "image": "company_images/anthropic/auto-e1fd44495c5890.png",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "company-searched-pool:anthropic:anthropic:v10",
    "image_provider": "company-searched-image-pool",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "미국",
    "매체": "TechCrunch",
    "제목": "YouTube finally launches a dedicated app for Apple Vision Pro",
    "링크": "https://techcrunch.com/2026/02/12/youtube-finally-launches-a-dedicated-app-for-apple-vision-pro/",
    "요약": "애플 비전 프로가 출시된 지 오랜 기다림 끝에 마침내 유튜브 전용 앱이 공식적으로 등장했습니다. 이제 사용자들은 웹 브라우저를 거치지 않고도 가상 현실 환경에 최적화된 몰입감 넘치는 영상 콘텐츠를 더욱 편리하게 즐길 수 있게 되었습니다.",
    "이미지": "company_images/google/auto-84cadac94443fe.png",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "company-searched-pool:google:youtube:v8",
    "이미지생성방식": "company-searched-image-pool",
    "country": "global",
    "media": "TechCrunch",
    "title": "YouTube finally launches a dedicated app for Apple Vision Pro",
    "link": "https://techcrunch.com/2026/02/12/youtube-finally-launches-a-dedicated-app-for-apple-vision-pro/",
    "summary": "애플 비전 프로가 출시된 지 오랜 기다림 끝에 마침내 유튜브 전용 앱이 공식적으로 등장했습니다. 이제 사용자들은 웹 브라우저를 거치지 않고도 가상 현실 환경에 최적화된 몰입감 넘치는 영상 콘텐츠를 더욱 편리하게 즐길 수 있게 되었습니다.",
    "image": "company_images/google/auto-84cadac94443fe.png",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "company-searched-pool:google:youtube:v8",
    "image_provider": "company-searched-image-pool",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "A surprise God of War prequel is out on the PS5 right now",
    "링크": "https://www.theverge.com/games/878375/god-of-war-sons-of-sparta-trilogy-sony-playstation-ps5-release-date-trailer",
    "요약": "전 세계적으로 사랑받는 게임 '갓 오브 워' 시리즈의 과거 이야기를 다룬 신작이 예고 없이 깜짝 출시되었습니다. 이번 작품은 기존의 화려한 3D 그래픽 대신 정겨운 2D 횡스크롤 방식을 채택하여, 주인공의 숨겨진 비화를 신선한 연출로 즐길 수 있습니다.",
    "이미지": "generated_images/a-surprise-god-of-war-prequel-is-out-on-51f3afdc04b7-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:gaming:playstation",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "The Verge",
    "title": "A surprise God of War prequel is out on the PS5 right now",
    "link": "https://www.theverge.com/games/878375/god-of-war-sons-of-sparta-trilogy-sony-playstation-ps5-release-date-trailer",
    "summary": "전 세계적으로 사랑받는 게임 '갓 오브 워' 시리즈의 과거 이야기를 다룬 신작이 예고 없이 깜짝 출시되었습니다. 이번 작품은 기존의 화려한 3D 그래픽 대신 정겨운 2D 횡스크롤 방식을 채택하여, 주인공의 숨겨진 비화를 신선한 연출로 즐길 수 있습니다.",
    "image": "generated_images/a-surprise-god-of-war-prequel-is-out-on-51f3afdc04b7-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:gaming:playstation",
    "image_provider": "simple-illustration",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "Ring cancels its partnership with Flock Safety after surveillance backlash",
    "링크": "https://www.theverge.com/news/878447/ring-flock-partnership-canceled",
    "요약": "아마존의 스마트 초인종 브랜드인 '링'이 경찰용 감시 기술 업체와의 협력 계획을 전격 취소했습니다. 이는 과도한 감시 시스템 구축에 따른 사생활 침해 논란이 거세지자, 사용자들의 개인정보 보호를 최우선으로 고려해 내린 결정입니다.",
    "이미지": "generated_images/ring-cancels-its-partnership-with-flock-e298ecbd9bb5-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:ai:ai",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "The Verge",
    "title": "Ring cancels its partnership with Flock Safety after surveillance backlash",
    "link": "https://www.theverge.com/news/878447/ring-flock-partnership-canceled",
    "summary": "아마존의 스마트 초인종 브랜드인 '링'이 경찰용 감시 기술 업체와의 협력 계획을 전격 취소했습니다. 이는 과도한 감시 시스템 구축에 따른 사생활 침해 논란이 거세지자, 사용자들의 개인정보 보호를 최우선으로 고려해 내린 결정입니다.",
    "image": "generated_images/ring-cancels-its-partnership-with-flock-e298ecbd9bb5-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:ai:ai",
    "image_provider": "simple-illustration",
    "curation_model": "models/gemini-3-flash-preview",
    "curation_mode": "curation-success"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "PlayStation State of Play February 2026: all the news and trailers",
    "링크": "https://www.theverge.com/games/877875/playstation-state-of-play-february-2026-ps5-news-trailers",
    "요약": "Strap in, because the next PlayStation event is going to be a long one. Sony’s latest State of Play — a showcase event for upcoming PS5 games — kicks off on February 12th at 5PM ET and it’ll last more than an hour. We don’t know what exactl...",
    "이미지": "generated_images/playstation-state-of-play-february-2026-c31a3f057e50-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:gaming:playstation",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "The Verge",
    "title": "PlayStation State of Play February 2026: all the news and trailers",
    "link": "https://www.theverge.com/games/877875/playstation-state-of-play-february-2026-ps5-news-trailers",
    "summary": "Strap in, because the next PlayStation event is going to be a long one. Sony’s latest State of Play — a showcase event for upcoming PS5 games — kicks off on February 12th at 5PM ET and it’ll last more than an hour. We don’t know what exactl...",
    "image": "generated_images/playstation-state-of-play-february-2026-c31a3f057e50-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:gaming:playstation",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "In one swoop, Trump kills US greenhouse gas regulations",
    "링크": "https://www.theverge.com/science/877371/trump-carbon-pollution-endangerment-finding-repeal-climate-change",
    "요약": "The Trump administration just eliminated the landmark finding that has underpinned federal regulations on planet-heating pollution since 2009. For nearly the past two decades, the \"endangerment finding\" has allowed the Environmental Protect...",
    "이미지": "generated_images/in-one-swoop-trump-kills-us-greenhouse-g-4ff50e473c56-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:ai:ai",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "The Verge",
    "title": "In one swoop, Trump kills US greenhouse gas regulations",
    "link": "https://www.theverge.com/science/877371/trump-carbon-pollution-endangerment-finding-repeal-climate-change",
    "summary": "The Trump administration just eliminated the landmark finding that has underpinned federal regulations on planet-heating pollution since 2009. For nearly the past two decades, the \"endangerment finding\" has allowed the Environmental Protect...",
    "image": "generated_images/in-one-swoop-trump-kills-us-greenhouse-g-4ff50e473c56-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:ai:ai",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "Two powerful, OLED-equipped gaming laptops are hundreds off",
    "링크": "https://www.theverge.com/gadgets/878209/asus-acer-oled-rtx-5070ti-gaming-laptop-deal-sale",
    "요약": "Whether you’re considering a 16-inch gaming laptop, or a more compact 14-inch model, there’s a deal with your name on it happening right now at Best Buy. The 2025 models of Acer’s Predator Helios Neo 16S and the Asus ROG Zephyrus G14 are hu...",
    "이미지": "generated_images/two-powerful-oled-equipped-gaming-laptop-729f1014136f-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:apple:ios",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "The Verge",
    "title": "Two powerful, OLED-equipped gaming laptops are hundreds off",
    "link": "https://www.theverge.com/gadgets/878209/asus-acer-oled-rtx-5070ti-gaming-laptop-deal-sale",
    "summary": "Whether you’re considering a 16-inch gaming laptop, or a more compact 14-inch model, there’s a deal with your name on it happening right now at Best Buy. The 2025 models of Acer’s Predator Helios Neo 16S and the Asus ROG Zephyrus G14 are hu...",
    "image": "generated_images/two-powerful-oled-equipped-gaming-laptop-729f1014136f-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:apple:ios",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "Eufy’s midrange X10 Pro Omni robovac has fallen to its best-ever price",
    "링크": "https://www.theverge.com/gadgets/877673/eufy-x10-pro-omni-nothing-phone-3-deal-sale",
    "요약": "Spring doesn’t officially kick off until March 20th, but there’s something to be said about getting a head start on your spring cleaning. Lucky for you, Eufy’s X10 Pro Omni is currently on sale at Amazon, Walmart, and directly from Eufy (wi...",
    "이미지": "generated_images/eufy-s-midrange-x10-pro-omni-robovac-has-3be0f193ffbe-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:amazon:amazon",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "The Verge",
    "title": "Eufy’s midrange X10 Pro Omni robovac has fallen to its best-ever price",
    "link": "https://www.theverge.com/gadgets/877673/eufy-x10-pro-omni-nothing-phone-3-deal-sale",
    "summary": "Spring doesn’t officially kick off until March 20th, but there’s something to be said about getting a head start on your spring cleaning. Lucky for you, Eufy’s X10 Pro Omni is currently on sale at Amazon, Walmart, and directly from Eufy (wi...",
    "image": "generated_images/eufy-s-midrange-x10-pro-omni-robovac-has-3be0f193ffbe-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:amazon:amazon",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "Jeffrey Epstein might not have created /pol/, but he helped carry out its mission",
    "링크": "https://www.theverge.com/tech/877903/jeffrey-epstein-4chan-pol-moot",
    "요약": "On October 24th, 2011, Jeffrey Epstein was emailing back and forth with Boris Nikolic, a biotech venture capitalist who would later be named as a backup executor of Epstein's will. The two appeared to be discussing a meeting Nikolic had hel...",
    "이미지": "generated_images/jeffrey-epstein-might-not-have-created-p-1d40ddc2fd29-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:ai:ai",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "The Verge",
    "title": "Jeffrey Epstein might not have created /pol/, but he helped carry out its mission",
    "link": "https://www.theverge.com/tech/877903/jeffrey-epstein-4chan-pol-moot",
    "summary": "On October 24th, 2011, Jeffrey Epstein was emailing back and forth with Boris Nikolic, a biotech venture capitalist who would later be named as a backup executor of Epstein's will. The two appeared to be discussing a meeting Nikolic had hel...",
    "image": "generated_images/jeffrey-epstein-might-not-have-created-p-1d40ddc2fd29-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:ai:ai",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "The Verge",
    "제목": "Good Luck, Have Fun, Don’t Die is a rollicking parable about this moment in tech",
    "링크": "https://www.theverge.com/entertainment/877244/good-luck-have-fun-dont-die-review",
    "요약": "We are all guilty of pulling out our phones and doomscrolling through stressful headlines or mindnumbing videos when we should be doing anything else. We know it's bad, but we still do it because it's hard to resist when much of our time is...",
    "이미지": "generated_images/good-luck-have-fun-don-t-die-is-a-rollic-2c84f8613a3a-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:general:none",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "The Verge",
    "title": "Good Luck, Have Fun, Don’t Die is a rollicking parable about this moment in tech",
    "link": "https://www.theverge.com/entertainment/877244/good-luck-have-fun-dont-die-review",
    "summary": "We are all guilty of pulling out our phones and doomscrolling through stressful headlines or mindnumbing videos when we should be doing anything else. We know it's bad, but we still do it because it's hard to resist when much of our time is...",
    "image": "generated_images/good-luck-have-fun-don-t-die-is-a-rollic-2c84f8613a3a-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:general:none",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "The Asus Zenbook S 16 Is $500 Off and Has Never Been This Cheap",
    "링크": "https://www.wired.com/story/asus-zenbook-s-16-presidents-day-sale/",
    "요약": "The Asus Zenbook S 16 was a favorite of ours last year, but the price was always too high. Now it has dropped to $1,000, and it’s a total steal.",
    "이미지": "generated_images/the-asus-zenbook-s-16-is-500-off-and-has-cc969b4995fa-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:general:none",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "Wired",
    "title": "The Asus Zenbook S 16 Is $500 Off and Has Never Been This Cheap",
    "link": "https://www.wired.com/story/asus-zenbook-s-16-presidents-day-sale/",
    "summary": "The Asus Zenbook S 16 was a favorite of ours last year, but the price was always too high. Now it has dropped to $1,000, and it’s a total steal.",
    "image": "generated_images/the-asus-zenbook-s-16-is-500-off-and-has-cc969b4995fa-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:general:none",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "‘Uncanny Valley’: ICE’s Secret Expansion Plans, Palantir Workers’ Ethical Concerns, and AI Assistants",
    "링크": "https://www.wired.com/story/uncanny-valley-podcast-ice-expansion-palantir-workers-ethical-concerns-openclaw-ai-assistants/",
    "요약": "In this episode of Uncanny Valley, our hosts dive into WIRED’s scoop about a secret Trump administration campaign extending right into your backyard.",
    "이미지": "company_images/palantir/auto-c07619ff4bc053.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "company-searched-pool:palantir:palantir:v7",
    "이미지생성방식": "company-searched-image-pool",
    "country": "global",
    "media": "Wired",
    "title": "‘Uncanny Valley’: ICE’s Secret Expansion Plans, Palantir Workers’ Ethical Concerns, and AI Assistants",
    "link": "https://www.wired.com/story/uncanny-valley-podcast-ice-expansion-palantir-workers-ethical-concerns-openclaw-ai-assistants/",
    "summary": "In this episode of Uncanny Valley, our hosts dive into WIRED’s scoop about a secret Trump administration campaign extending right into your backyard.",
    "image": "company_images/palantir/auto-c07619ff4bc053.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "company-searched-pool:palantir:palantir:v7",
    "image_provider": "company-searched-image-pool",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "Waymo Asks the DC Public to Pressure Their City Officials",
    "링크": "https://www.wired.com/story/waymo-asks-the-dc-public-to-pressure-their-city-officials/",
    "요약": "Stuck in regulatory limbo, the self-driving-vehicle developer is encouraging residents of Washington, DC, to message public officials to help get its robotaxis onto roads.",
    "이미지": "generated_images/waymo-asks-the-dc-public-to-pressure-the-408bb2379baa-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:robotics:robot",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "Wired",
    "title": "Waymo Asks the DC Public to Pressure Their City Officials",
    "link": "https://www.wired.com/story/waymo-asks-the-dc-public-to-pressure-their-city-officials/",
    "summary": "Stuck in regulatory limbo, the self-driving-vehicle developer is encouraging residents of Washington, DC, to message public officials to help get its robotaxis onto roads.",
    "image": "generated_images/waymo-asks-the-dc-public-to-pressure-the-408bb2379baa-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:robotics:robot",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "A Wave of Unexplained Bot Traffic Is Sweeping the Web",
    "링크": "https://www.wired.com/story/made-in-china-niche-websites-are-seeing-a-surge-of-mysterious-traffic-from-china/",
    "요약": "From small publishers to US federal agencies, websites are reporting unusual spikes in automated traffic linked to IP addresses in Lanzhou, China.",
    "이미지": "generated_images/a-wave-of-unexplained-bot-traffic-is-swe-d235b14608d4-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:ai:ai",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "Wired",
    "title": "A Wave of Unexplained Bot Traffic Is Sweeping the Web",
    "link": "https://www.wired.com/story/made-in-china-niche-websites-are-seeing-a-surge-of-mysterious-traffic-from-china/",
    "summary": "From small publishers to US federal agencies, websites are reporting unusual spikes in automated traffic linked to IP addresses in Lanzhou, China.",
    "image": "generated_images/a-wave-of-unexplained-bot-traffic-is-swe-d235b14608d4-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:ai:ai",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "OpenAI’s President Gave Millions to Trump. He Says It’s for Humanity",
    "링크": "https://www.wired.com/story/openai-president-greg-brockman-political-donations-trump-humanity/",
    "요약": "In an interview with WIRED, Greg Brockman says his political donations support OpenAI's mission—even if some employees at the company disagree.",
    "이미지": "company_images/openai/auto-2ad66714d9bd46.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "company-searched-pool:openai:openai:v3",
    "이미지생성방식": "company-searched-image-pool",
    "country": "global",
    "media": "Wired",
    "title": "OpenAI’s President Gave Millions to Trump. He Says It’s for Humanity",
    "link": "https://www.wired.com/story/openai-president-greg-brockman-political-donations-trump-humanity/",
    "summary": "In an interview with WIRED, Greg Brockman says his political donations support OpenAI's mission—even if some employees at the company disagree.",
    "image": "company_images/openai/auto-2ad66714d9bd46.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "company-searched-pool:openai:openai:v3",
    "image_provider": "company-searched-image-pool",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "Our Favorite TV Is Still Almost Half Off",
    "링크": "https://www.wired.com/story/tcl-qm6k-deal-226/",
    "요약": "Best Buy continues to sell the TCL QM6K for a staggering discount.",
    "이미지": "generated_images/our-favorite-tv-is-still-almost-half-off-982a80ecc5c4-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:general:none",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "Wired",
    "title": "Our Favorite TV Is Still Almost Half Off",
    "link": "https://www.wired.com/story/tcl-qm6k-deal-226/",
    "summary": "Best Buy continues to sell the TCL QM6K for a staggering discount.",
    "image": "generated_images/our-favorite-tv-is-still-almost-half-off-982a80ecc5c4-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:general:none",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "Elon Musk’s X Appears to Be Violating US Sanctions by Selling Premium Accounts to Iranian Leaders",
    "링크": "https://www.wired.com/story/elon-musk-x-premium-accounts-iran/",
    "요약": "While publicly supporting protesters in Iran, Elon Musk’s X appears to have been selling premium accounts to regime officials. Check marks were removed from certain accounts after a WIRED inquiry.",
    "이미지": "generated_images/elon-musk-s-x-appears-to-be-violating-us-8c185a4f9f3f-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:ai:ai",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "Wired",
    "title": "Elon Musk’s X Appears to Be Violating US Sanctions by Selling Premium Accounts to Iranian Leaders",
    "link": "https://www.wired.com/story/elon-musk-x-premium-accounts-iran/",
    "summary": "While publicly supporting protesters in Iran, Elon Musk’s X appears to have been selling premium accounts to regime officials. Check marks were removed from certain accounts after a WIRED inquiry.",
    "image": "generated_images/elon-musk-s-x-appears-to-be-violating-us-8c185a4f9f3f-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:ai:ai",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Wired",
    "제목": "How to Choose the Right TV in 2026 (and a Few We Like)",
    "링크": "https://www.wired.com/story/how-to-buy-the-right-tv/",
    "요약": "How many ports do you need? What does 4K UHD even mean? What's RGB LED? Here’s everything you need to know.",
    "이미지": "generated_images/how-to-choose-the-right-tv-in-2026-and-a-34a68e797e26-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:general:none",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "Wired",
    "title": "How to Choose the Right TV in 2026 (and a Few We Like)",
    "link": "https://www.wired.com/story/how-to-buy-the-right-tv/",
    "summary": "How many ports do you need? What does 4K UHD even mean? What's RGB LED? Here’s everything you need to know.",
    "image": "generated_images/how-to-choose-the-right-tv-in-2026-and-a-34a68e797e26-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:general:none",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "When Amazon badly needed a ride, Europe's Ariane 6 rocket delivered",
    "링크": "https://arstechnica.com/space/2026/02/when-amazon-badly-needed-a-ride-europes-ariane-6-rocket-delivered/",
    "요약": "This was the first launch of the Ariane 64, the most powerful rocket in European space history.",
    "이미지": "company_images/amazon/auto-1cbe36adfc882a.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "company-searched-pool:amazon:amazon:v2",
    "이미지생성방식": "company-searched-image-pool",
    "country": "global",
    "media": "Ars Technica",
    "title": "When Amazon badly needed a ride, Europe's Ariane 6 rocket delivered",
    "link": "https://arstechnica.com/space/2026/02/when-amazon-badly-needed-a-ride-europes-ariane-6-rocket-delivered/",
    "summary": "This was the first launch of the Ariane 64, the most powerful rocket in European space history.",
    "image": "company_images/amazon/auto-1cbe36adfc882a.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "company-searched-pool:amazon:amazon:v2",
    "image_provider": "company-searched-image-pool",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "OpenAI sidesteps Nvidia with unusually fast coding model on plate-sized chips",
    "링크": "https://arstechnica.com/ai/2026/02/openai-sidesteps-nvidia-with-unusually-fast-coding-model-on-plate-sized-chips/",
    "요약": "OpenAI's new GPT‑5.3‑Codex‑Spark is 15 times faster at coding than its predecessor.",
    "이미지": "company_images/openai/auto-e9e35d28324a87.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "company-searched-pool:openai:openai:v10",
    "이미지생성방식": "company-searched-image-pool",
    "country": "global",
    "media": "Ars Technica",
    "title": "OpenAI sidesteps Nvidia with unusually fast coding model on plate-sized chips",
    "link": "https://arstechnica.com/ai/2026/02/openai-sidesteps-nvidia-with-unusually-fast-coding-model-on-plate-sized-chips/",
    "summary": "OpenAI's new GPT‑5.3‑Codex‑Spark is 15 times faster at coding than its predecessor.",
    "image": "company_images/openai/auto-e9e35d28324a87.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "company-searched-pool:openai:openai:v10",
    "image_provider": "company-searched-image-pool",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "Trump official overruled FDA scientists to reject Moderna's flu shot",
    "링크": "https://arstechnica.com/health/2026/02/trump-official-overruled-fda-scientists-to-reject-modernas-flu-shot/",
    "요약": "FDA's top vaccine regulator, Vinay Prasad, is known for overruling scientists.",
    "이미지": "generated_images/trump-official-overruled-fda-scientists-5b5c16f77aab-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:general:none",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "Ars Technica",
    "title": "Trump official overruled FDA scientists to reject Moderna's flu shot",
    "link": "https://arstechnica.com/health/2026/02/trump-official-overruled-fda-scientists-to-reject-modernas-flu-shot/",
    "summary": "FDA's top vaccine regulator, Vinay Prasad, is known for overruling scientists.",
    "image": "generated_images/trump-official-overruled-fda-scientists-5b5c16f77aab-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:general:none",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "Spider-Noir teaser comes in colorized \"True Hue\" and black and white",
    "링크": "https://arstechnica.com/culture/2026/02/spider-noir-teaser-comes-in-colorized-true-hue-and-black-and-white/",
    "요약": "Nicolas Cage described his character as \"70 percent Humphrey Bogart and 30 percent Bugs Bunny.\"",
    "이미지": "generated_images/spider-noir-teaser-comes-in-colorized-tr-f7f8ae1eee09-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:general:none",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "Ars Technica",
    "title": "Spider-Noir teaser comes in colorized \"True Hue\" and black and white",
    "link": "https://arstechnica.com/culture/2026/02/spider-noir-teaser-comes-in-colorized-true-hue-and-black-and-white/",
    "summary": "Nicolas Cage described his character as \"70 percent Humphrey Bogart and 30 percent Bugs Bunny.\"",
    "image": "generated_images/spider-noir-teaser-comes-in-colorized-tr-f7f8ae1eee09-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:general:none",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "ULA's Vulcan rocket suffers another booster problem on the way to orbit",
    "링크": "https://arstechnica.com/space/2026/02/ulas-vulcan-launcher-still-has-a-solid-rocket-booster-problem/",
    "요약": "Vulcan's Blue Origin-made BE-4 engines appear to have saved the rocket from failure.",
    "이미지": "generated_images/ula-s-vulcan-rocket-suffers-another-boos-d9aed7194de6-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:space:rocket",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "Ars Technica",
    "title": "ULA's Vulcan rocket suffers another booster problem on the way to orbit",
    "link": "https://arstechnica.com/space/2026/02/ulas-vulcan-launcher-still-has-a-solid-rocket-booster-problem/",
    "summary": "Vulcan's Blue Origin-made BE-4 engines appear to have saved the rocket from failure.",
    "image": "generated_images/ula-s-vulcan-rocket-suffers-another-boos-d9aed7194de6-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:space:rocket",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "EPA kills foundation of greenhouse gas regulations",
    "링크": "https://arstechnica.com/tech-policy/2026/02/as-expected-trumps-epa-guts-climate-endangerment-finding/",
    "요약": "The agency is betting the the Supreme Court will reverse a prior ruling.",
    "이미지": "generated_images/epa-kills-foundation-of-greenhouse-gas-r-813d32abaf61-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:general:none",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "Ars Technica",
    "title": "EPA kills foundation of greenhouse gas regulations",
    "link": "https://arstechnica.com/tech-policy/2026/02/as-expected-trumps-epa-guts-climate-endangerment-finding/",
    "summary": "The agency is betting the the Supreme Court will reverse a prior ruling.",
    "image": "generated_images/epa-kills-foundation-of-greenhouse-gas-r-813d32abaf61-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:general:none",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "Trump FTC wants Apple News to promote more Fox News and Breitbart stories",
    "링크": "https://arstechnica.com/tech-policy/2026/02/trump-ftc-denies-being-speech-police-but-says-apple-news-is-too-liberal/",
    "요약": "FTC claims Apple News suppresses conservatives, cites study by pro-Trump group.",
    "이미지": "company_images/apple/auto-79da636c831445.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "company-searched-pool:apple:apple:v2",
    "이미지생성방식": "company-searched-image-pool",
    "country": "global",
    "media": "Ars Technica",
    "title": "Trump FTC wants Apple News to promote more Fox News and Breitbart stories",
    "link": "https://arstechnica.com/tech-policy/2026/02/trump-ftc-denies-being-speech-police-but-says-apple-news-is-too-liberal/",
    "summary": "FTC claims Apple News suppresses conservatives, cites study by pro-Trump group.",
    "image": "company_images/apple/auto-79da636c831445.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "company-searched-pool:apple:apple:v2",
    "image_provider": "company-searched-image-pool",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  },
  {
    "국가": "미국",
    "매체": "Ars Technica",
    "제목": "DIY PC maker Framework has needed monthly price hikes to navigate the RAM shortage",
    "링크": "https://arstechnica.com/gadgets/2026/02/frameworks-ram-prices-climbing-on-a-monthly-cadence-with-more-hikes-to-come/",
    "요약": "And Framework expects things to get worse before they get better.",
    "이미지": "generated_images/diy-pc-maker-framework-has-needed-monthl-7c5425ae586b-simple.svg",
    "수집일시": "2026-02-13 10:53",
    "이미지프롬프트": "simple-illustration:general:none",
    "이미지생성방식": "simple-illustration",
    "country": "global",
    "media": "Ars Technica",
    "title": "DIY PC maker Framework has needed monthly price hikes to navigate the RAM shortage",
    "link": "https://arstechnica.com/gadgets/2026/02/frameworks-ram-prices-climbing-on-a-monthly-cadence-with-more-hikes-to-come/",
    "summary": "And Framework expects things to get worse before they get better.",
    "image": "generated_images/diy-pc-maker-framework-has-needed-monthl-7c5425ae586b-simple.svg",
    "collected_at": "2026-02-13 10:53",
    "image_prompt": "simple-illustration:general:none",
    "image_provider": "simple-illustration",
    "curation_model": "",
    "curation_mode": "curation-limit-reached"
  }
];